//! The JIT engine provided by JavaScript (ADR 0012 and 0013, `docs/specs/jit.md`,
//! `docs/specs/wasm.md`).
//!
//! In the browser and in Node the modules generated by the translator are compiled and
//! run by JS's `WebAssembly` API (`web/node/jit-engine.mjs`). This
//! module is the Rust side of the bridge:
//! - [`JsEngine`] implements `vetro_jit::Engine` by calling the JS imports
//!   `vetro_jit.compile/run/drop/place/reset`;
//! - JS instantiates every generated module with `env.mem` = the memory of
//!   this module and `env.ld`/`env.st` = the exports [`vetro_jit_ld`] and
//!   [`vetro_jit_st`], which call back the [`Host`] of the running block; the
//!   dispatcher also imports `env.tbl`, the block table, into which
//!   JS puts the modules' functions (`vetro_jit.place`).
//!
//! Since `env.mem` is the whole vetro-wasm memory, the blocks also reach
//! the guest RAM directly ([`Engine::host_address`]): the system-mode software
//! TLB points into it.
//!
//! [`vetro_jit_selftest`] tests the full round trip (Rust → JS → generated
//! module → `ld`/`st` in Rust) with a module written by the JS test.

use core::cell::Cell;

use vetro_jit::state::off;
use vetro_jit::{Engine, FAULT, Host, NEXT, STOP};

/// Size of the shared memory of a [`JsEngine`]: `JitState` and
/// the system-mode area (`vetro_jit::state::area`).
/// How the generated modules import `env.mem` (vetro-wasm's own memory):
/// shared, with the 4 GiB maximum of the threads build (`tools/wasm-threads.sh`,
/// ADR 0042), when this module is built with atomics; otherwise an ordinary
/// memory. An import must match the memory it is given: a shared memory only
/// links to a shared import with the same maximum.
pub fn memory_import() -> vetro_jit::wasm::MemoryImport {
    vetro_jit::wasm::MemoryImport { min: 1, shared_max: THREADS.then_some(65536) }
}

/// True in the threads build (atomics and a shared memory).
pub const THREADS: bool = cfg!(target_feature = "atomics");

pub const SHARED_LEN: usize = 256 * 1024;

#[repr(C, align(16))]
struct Shared([u8; SHARED_LEN]);

/// A module compiled by JS: an index into its table.
#[derive(Debug)]
pub struct JsModule(i32);

/// The engine that delegates to JS's `WebAssembly`. The shared memory is a
/// buffer of this module: its address plus `state` is what the
/// block receives, because for the block `env.mem` is the whole linear memory.
pub struct JsEngine {
    shared: Box<Shared>,
    /// Last function run: (module, index, entry in the vetro-wasm function
    /// table). The dispatcher runs at every run.
    last: Option<(i32, u32, usize)>,
}

impl Default for JsEngine {
    fn default() -> Self {
        // SAFETY: all zeros is a valid value for a byte array.
        JsEngine { shared: unsafe { Box::<Shared>::new_zeroed().assume_init() }, last: None }
    }
}

impl JsEngine {
    /// Entry of the vetro-wasm function table with the module's `b<index>`:
    /// JS puts it there the first time (`vetro_jit.entry`), then
    /// Rust calls it as a function pointer, without going through JS.
    fn entry(&mut self, m: &JsModule, index: u32) -> usize {
        match self.last {
            Some((id, i, e)) if id == m.0 && i == index => e,
            _ => {
                // SAFETY: JS import.
                let e = unsafe { js::entry(m.0, index) } as usize;
                self.last = Some((m.0, index, e));
                e
            }
        }
    }
}

impl Engine for JsEngine {
    type Module = JsModule;

    fn runtime(&mut self, wasm: &[u8]) -> Result<(), String> {
        // SAFETY: JS import, reads `wasm` during the call.
        let r = unsafe { js::runtime(wasm.as_ptr(), wasm.len()) };
        if r < 0 { Err(format!("the JS engine refused the runtime ({r})")) } else { Ok(()) }
    }

    fn compile(&mut self, wasm: &[u8]) -> Result<JsModule, String> {
        // SAFETY: JS import, reads `wasm` during the call.
        let id = unsafe { js::compile(wasm.as_ptr(), wasm.len()) };
        if id < 0 { Err(format!("the JS engine refused the module ({id})")) } else { Ok(JsModule(id)) }
    }

    /// ADR 0038: with background compilation (`JitEngine` in async mode) a
    /// module may still be compiling in a Worker.
    fn ready(&mut self, m: &JsModule) -> bool {
        // SAFETY: JS import, no memory access.
        unsafe { js::ready(m.0) != 0 }
    }

    /// Runs block `b<index>` on the state at offset `state` of the
    /// shared memory; during execution `ld`/`st` call `host`.
    fn run(&mut self, m: &JsModule, index: u32, state: u32, host: &mut dyn Host) -> u32 {
        assert!(state as usize + off::SIZE <= SHARED_LEN && state.is_multiple_of(16), "JitState misplaced");
        let base = self.shared.0.as_mut_ptr();
        let addr = base as usize + state as usize;
        let mut h: &mut dyn Host = host;
        let prev = HOST.replace((&mut h as *mut &mut dyn Host).cast());
        let prev_mem = MEM.replace(base);
        let entry = self.entry(m, index);
        // SAFETY: the `entry` of the table is the module's function `b<index>`,
        // of type (i32) -> i32; the block writes only into the
        // shared memory and the guest RAM (through the software TLB),
        // and calls `ld`/`st`/`resolve`, which use `h` while it is alive.
        let r = unsafe { js::call(entry, addr) };
        HOST.set(prev);
        MEM.set(prev_mem);
        r
    }

    fn memory(&mut self) -> &mut [u8] {
        &mut self.shared.0
    }

    fn place(&mut self, m: &JsModule, count: u32, base: u32) {
        // SAFETY: JS import: puts the exports into the block table.
        unsafe { js::place(m.0, count, base) }
    }

    fn reset(&mut self) {
        // SAFETY: JS import: discards instances and table.
        unsafe { js::reset() }
    }

    /// In wasm32 `env.mem` is the memory of this module: every one of its bytes has
    /// the pointer itself as its address.
    fn host_address(&mut self, p: *const u8, len: usize) -> Option<u32> {
        if cfg!(target_arch = "wasm32") {
            let a = p as usize as u64;
            (a + len as u64 <= 1 << 32).then_some(a as u32)
        } else {
            None
        }
    }
}

impl Drop for JsModule {
    fn drop(&mut self) {
        // SAFETY: JS import; the index is no longer used.
        unsafe { js::drop_module(self.0) }
    }
}

thread_local! {
    /// The `Host` of the running block: an untyped `*mut &mut dyn Host`.
    static HOST: Cell<*mut ()> = const { Cell::new(core::ptr::null_mut()) };
    /// The shared memory of the running engine.
    static MEM: Cell<*mut u8> = const { Cell::new(core::ptr::null_mut()) };
}

fn with_host<R>(f: impl FnOnce(&mut dyn Host, &mut [u8]) -> R) -> R {
    let p = HOST.get().cast::<&mut dyn Host>();
    let m = MEM.get();
    assert!(!p.is_null() && !m.is_null(), "ld/st outside a block");
    // SAFETY: set by `JsEngine::run` for the duration of the call to
    // JS; while `ld`/`st` run nobody else uses the shared memory.
    let mem = unsafe { core::slice::from_raw_parts_mut(m, SHARED_LEN) };
    f(unsafe { &mut **p }, mem)
}

/// `env.ld` of the generated modules: read of `size` bytes, zero-extended. On
/// a fault writes `FAULT` into `exit_detail` and returns 0.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn vetro_jit_ld(state: usize, va: u64, size: u32) -> u64 {
    match with_host(|h, mem| h.ld(mem, va, size)) {
        Ok(v) => v,
        Err(()) => {
            // SAFETY: `state` is the address of a `JitState` (contract).
            unsafe { set_exit_detail(state, FAULT) };
            0
        }
    }
}

/// `env.st` of the generated modules: 0 = continue, 1 = the block stops
/// (fault, with `FAULT` in `exit_detail`, or write to watched code,
/// with `STOP`).
#[unsafe(no_mangle)]
pub unsafe extern "C" fn vetro_jit_st(state: usize, va: u64, size: u32, value: u64) -> u32 {
    match with_host(|h, mem| h.st(mem, va, size, value)) {
        Ok(false) => 0,
        Ok(true) => {
            // SAFETY: as below.
            unsafe { set_exit_detail(state, STOP) };
            1
        }
        Err(()) => {
            // SAFETY: `state` is the address of a `JitState` (contract).
            unsafe { set_exit_detail(state, FAULT) };
            1
        }
    }
}

/// `env.resolve` of the dispatcher: 1 if the host wrote the jump cache
/// entry for the `pc` of `JitState`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn vetro_jit_resolve(_state: usize) -> u32 {
    with_host(|h, mem| h.resolve(mem)) as u32
}

/// `env.vsync` of the runtime: the SIMD/FP registers of the `Cpu` in the `JitState`
/// at the (absolute) address `state`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn vetro_jit_vsync(state: usize) {
    let base = MEM.get() as usize;
    with_host(|h, mem| h.vsync(mem, (state - base) as u32))
}

/// `env.simd` of the runtime (ADR 0026): a SIMD/FP instruction without memory
/// executed by the interpreter on the `JitState` at the (absolute) address `state`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn vetro_jit_simd(state: usize, word: u32, x: u64, nzcv: u32) -> u64 {
    // SAFETY: `state` is the address of a 16-aligned `JitState` in the
    // shared memory (contract of the generated modules); nobody else
    // uses it while the region calls `env.simd`.
    let st = unsafe { core::slice::from_raw_parts_mut(state as *mut u8, off::SIZE) };
    vetro_jit::helper::exec(st, 0, word, x, nzcv)
}

unsafe fn set_exit_detail(state: usize, v: u32) {
    let p = (state + off::EXIT_DETAIL as usize) as *mut u32;
    // SAFETY: `state` points to a 16-aligned `JitState` (contract).
    unsafe { p.write(v) }
}

#[cfg(target_arch = "wasm32")]
mod js {
    #[link(wasm_import_module = "vetro_jit")]
    unsafe extern "C" {
        /// Compiles a generated module; index >= 0, or < 0 if refused.
        pub fn compile(ptr: *const u8, len: usize) -> i32;
        /// Installs the runtime module (import `rt.*` of the modules); 0, or
        /// < 0 if refused.
        pub fn runtime(ptr: *const u8, len: usize) -> i32;
        /// Puts the export `b<index>` of the module into a new entry of the
        /// vetro-wasm function table; returns the entry.
        pub fn entry(module: i32, index: u32) -> u32;
        /// Frees the module.
        #[link_name = "drop"]
        pub fn drop_module(module: i32);
        /// Puts the exports `b0..b<count-1>` of the module into the entries
        /// `base..` of the block table.
        pub fn place(module: i32, count: u32, base: u32);
        /// Discards all instances and recreates the block table.
        pub fn reset();
        /// 1 if the module can run, 0 while a Worker still compiles it
        /// (ADR 0038).
        pub fn ready(module: i32) -> u32;
    }

    /// Calls the function at entry `entry` of the function table
    /// (a function pointer in wasm32) with `state`.
    ///
    /// # Safety
    /// `entry` must be a function of type (i32) -> i32.
    pub unsafe fn call(entry: usize, state: usize) -> u32 {
        // SAFETY: see above; in wasm32 a function pointer is its
        // entry in the table.
        let f = unsafe { core::mem::transmute::<usize, extern "C" fn(usize) -> u32>(entry) };
        f(state)
    }
}

/// Outside wasm32 there is no JS engine: the native engine is wasmtime
/// (`vetro-jit-native`).
#[cfg(not(target_arch = "wasm32"))]
mod js {
    pub unsafe fn compile(_ptr: *const u8, _len: usize) -> i32 {
        -1
    }
    pub unsafe fn runtime(_ptr: *const u8, _len: usize) -> i32 {
        -1
    }
    pub unsafe fn entry(_module: i32, _index: u32) -> u32 {
        unreachable!("no compiled module outside wasm32")
    }
    pub unsafe fn call(_entry: usize, _state: usize) -> u32 {
        unreachable!("no compiled module outside wasm32")
    }
    pub unsafe fn drop_module(_module: i32) {}
    pub unsafe fn place(_module: i32, _count: u32, _base: u32) {}
    pub unsafe fn reset() {}
    pub unsafe fn ready(_module: i32) -> u32 {
        1
    }
}

/// Flat test RAM for [`vetro_jit_selftest`]: 4 KiB from `SELFTEST_BASE`.
pub const SELFTEST_BASE: u64 = 0x1000;

struct TestRam([u8; 4096]);

impl Host for TestRam {
    fn ld(&mut self, _mem: &mut [u8], va: u64, size: u32) -> Result<u64, ()> {
        let o = va.checked_sub(SELFTEST_BASE).ok_or(())? as usize;
        let b = self.0.get(o..o + size as usize).ok_or(())?;
        let mut v = [0u8; 8];
        v[..b.len()].copy_from_slice(b);
        Ok(u64::from_le_bytes(v))
    }
    fn st(&mut self, _mem: &mut [u8], va: u64, size: u32, value: u64) -> Result<bool, ()> {
        let o = va.checked_sub(SELFTEST_BASE).ok_or(())? as usize;
        let b = self.0.get_mut(o..o + size as usize).ok_or(())?;
        b.copy_from_slice(&value.to_le_bytes()[..size as usize]);
        Ok(false)
    }
}

/// Test of the JIT bridge: compiles `wasm` with the JS engine and runs `b0` on a
/// `JitState` with `x0 = SELFTEST_BASE`, `x1 = 5`, `pc = 0x40_0000`, over a
/// RAM that contains 37 at `SELFTEST_BASE`. The test module
/// (`web/node/jit-selftest.mjs`) does `x2 = [x0] + x1; [x0 + 8] = x2`,
/// `pc += 12`, `steps += 3`. Returns the value at `SELFTEST_BASE + 8`
/// (42), or `u64::MAX - code` if something doesn't add up.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn vetro_jit_selftest(wasm: *const u8, len: usize) -> u64 {
    // SAFETY: `wasm` is valid for `len` bytes (contract).
    let wasm = unsafe { crate::bytes(wasm, len) };
    let mut e = JsEngine::default();
    let Ok(m) = e.compile(wasm) else { return u64::MAX - 1 };
    let mem = e.memory();
    mem[..off::SIZE].fill(0);
    mem[0..8].copy_from_slice(&SELFTEST_BASE.to_le_bytes());
    mem[8..16].copy_from_slice(&5u64.to_le_bytes());
    let pc = off::PC as usize;
    mem[pc..pc + 8].copy_from_slice(&0x40_0000u64.to_le_bytes());
    let mut ram = TestRam([0; 4096]);
    ram.0[..8].copy_from_slice(&37u64.to_le_bytes());
    if e.run(&m, 0, 0, &mut ram) != NEXT {
        return u64::MAX - 2;
    }
    let mem = e.memory();
    let rd = |o: u32| u64::from_le_bytes(mem[o as usize..o as usize + 8].try_into().unwrap());
    if rd(off::PC) != 0x40_000c || rd(off::STEPS) != 3 {
        return u64::MAX - 3;
    }
    u64::from_le_bytes(ram.0[8..16].try_into().unwrap())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ram_di_prova() {
        let mut r = TestRam([0; 4096]);
        let m = &mut [][..];
        assert_eq!(r.st(m, SELFTEST_BASE + 2, 2, 0xabcd), Ok(false));
        assert_eq!(r.ld(m, SELFTEST_BASE, 4), Ok(0xabcd_0000));
        assert_eq!(r.ld(m, SELFTEST_BASE + 4095, 2), Err(()));
        assert_eq!(r.ld(m, 0, 1), Err(()));
    }

    /// `ld`/`st` go through the host set by `run` and report faults in
    /// `exit_detail`: here host and memory are set by the test, as `run`
    /// would do.
    #[test]
    fn ld_st_verso_host() {
        let mut e = JsEngine::default();
        let base = e.memory().as_mut_ptr();
        let state = base as usize;
        let mut ram = TestRam([0; 4096]);
        let mut h: &mut dyn Host = &mut ram;
        HOST.set((&mut h as *mut &mut dyn Host).cast());
        MEM.set(base);
        unsafe {
            assert_eq!(vetro_jit_st(state, SELFTEST_BASE, 8, 7), 0);
            assert_eq!(vetro_jit_ld(state, SELFTEST_BASE, 8), 7);
            assert_eq!(vetro_jit_ld(state, 0, 8), 0);
        }
        HOST.set(core::ptr::null_mut());
        MEM.set(core::ptr::null_mut());
        let m = e.memory();
        let d = off::EXIT_DETAIL as usize;
        assert_eq!(u32::from_le_bytes(m[d..d + 4].try_into().unwrap()), FAULT);
        assert!(e.compile(&[0]).is_err(), "no JS engine outside wasm32");
        assert_eq!(e.host_address(base, 16), None, "outside wasm32 the RAM is not reachable");
    }
}
