#!/bin/busybox sh
# /init dell'initramfs di Vetro (M3): monta i file system virtuali, stampa il
# marcatore di avvio, esegue l'autotest e apre una shell sulla console.
# Parametri dalla riga di comando del kernel:
#   vetro.noautotest  salta l'autotest;
#   vetro.poweroff    spegne la macchina (PSCI) dopo l'autotest, senza shell;
#   vetro.kselftest   esegue i kselftest (/etc/kselftest.sh, initramfs dei
#                     kselftest) e spegne la macchina.
/bin/busybox --install -s
export PATH=/bin:/sbin:/usr/bin:/usr/sbin
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev
mount -t tmpfs tmpfs /tmp
echo "VETRO-BOOT-OK: /init avviato ($(uname -r))"
cmdline=$(cat /proc/cmdline)
case " $cmdline " in
  *" vetro.noautotest "*) ;;
  *) sh /etc/autotest.sh ;;
esac
case " $cmdline " in
  *" vetro.kselftest "*)
    echo "VETRO-KSELFTEST-INIZIO"
    sh /etc/kselftest.sh
    echo "VETRO-KSELFTEST-FINE"
    poweroff -f ;;
esac
case " $cmdline " in
  *" vetro.poweroff "*) poweroff -f ;;
esac
# Shell interattiva con terminale di controllo sulla console vera
# (/dev/console non può diventare terminale di controllo). La BusyBox di
# Alpine non ha cttyhack: si apre direttamente la PL011. Se esce, se ne apre
# un'altra.
tty=/dev/ttyAMA0
[ -c "$tty" ] || tty=/dev/console
while true; do
  setsid sh -c "exec sh -l <>$tty >&0 2>&1"
done
