// Generated by tools/gfxstream/gen-tables.py from spec/*.in, *.attrib, *.types
// (gfxstream emugen specs, Apache 2.0). Do not edit.

use crate::wire::{Op, P};

pub const RC_BASE: u32 = 10000;
pub static RC: [Op; 70] = [
    Op { name: "rcGetRendererVersion", params: &[], ret: 4 },
    Op { name: "rcGetEGLVersion", params: &[P::Out, P::Out], ret: 4 },
    Op { name: "rcQueryEGLString", params: &[P::S4, P::Out, P::S4], ret: 4 },
    Op { name: "rcGetGLString", params: &[P::S4, P::Out, P::S4], ret: 4 },
    Op { name: "rcGetNumConfigs", params: &[P::Out], ret: 4 },
    Op { name: "rcGetConfigs", params: &[P::S4, P::Out], ret: 4 },
    Op { name: "rcChooseConfig", params: &[P::In, P::S4, P::Out, P::S4], ret: 4 },
    Op { name: "rcGetFBParam", params: &[P::S4], ret: 4 },
    Op { name: "rcCreateContext", params: &[P::S4, P::S4, P::S4], ret: 4 },
    Op { name: "rcDestroyContext", params: &[P::S4], ret: 0 },
    Op { name: "rcCreateWindowSurface", params: &[P::S4, P::S4, P::S4], ret: 4 },
    Op { name: "rcDestroyWindowSurface", params: &[P::S4], ret: 0 },
    Op { name: "rcCreateColorBuffer", params: &[P::S4, P::S4, P::S4], ret: 4 },
    Op { name: "rcOpenColorBuffer", params: &[P::S4], ret: 0 },
    Op { name: "rcCloseColorBuffer", params: &[P::S4], ret: 0 },
    Op { name: "rcSetWindowColorBuffer", params: &[P::S4, P::S4], ret: 0 },
    Op { name: "rcFlushWindowColorBuffer", params: &[P::S4], ret: 4 },
    Op { name: "rcMakeCurrent", params: &[P::S4, P::S4, P::S4], ret: 4 },
    Op { name: "rcFBPost", params: &[P::S4], ret: 0 },
    Op { name: "rcFBSetSwapInterval", params: &[P::S4], ret: 0 },
    Op { name: "rcBindTexture", params: &[P::S4], ret: 0 },
    Op { name: "rcBindRenderbuffer", params: &[P::S4], ret: 0 },
    Op { name: "rcColorBufferCacheFlush", params: &[P::S4, P::S4, P::S4], ret: 4 },
    Op {
        name: "rcReadColorBuffer",
        params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::Out],
        ret: 0,
    },
    Op {
        name: "rcUpdateColorBuffer",
        params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::In],
        ret: 4,
    },
    Op { name: "rcOpenColorBuffer2", params: &[P::S4], ret: 4 },
    Op { name: "rcCreateClientImage", params: &[P::S4, P::S4, P::S4], ret: 4 },
    Op { name: "rcDestroyClientImage", params: &[P::S4], ret: 4 },
    Op { name: "rcSelectChecksumHelper", params: &[P::S4, P::S4], ret: 0 },
    Op { name: "rcCreateSyncKHR", params: &[P::S4, P::In, P::S4, P::S4, P::Out, P::Out], ret: 0 },
    Op { name: "rcClientWaitSyncKHR", params: &[P::S8, P::S4, P::S8], ret: 4 },
    Op { name: "rcFlushWindowColorBufferAsync", params: &[P::S4], ret: 0 },
    Op { name: "rcDestroySyncKHR", params: &[P::S8], ret: 4 },
    Op { name: "rcSetPuid", params: &[P::S8], ret: 0 },
    Op {
        name: "rcUpdateColorBufferDMA",
        params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S8, P::S4],
        ret: 4,
    },
    Op { name: "rcCreateColorBufferDMA", params: &[P::S4, P::S4, P::S4, P::S4], ret: 4 },
    Op { name: "rcWaitSyncKHR", params: &[P::S8, P::S4], ret: 0 },
    Op { name: "rcCompose", params: &[P::S4, P::In], ret: 4 },
    Op { name: "rcCreateDisplay", params: &[P::Out], ret: 4 },
    Op { name: "rcDestroyDisplay", params: &[P::S4], ret: 4 },
    Op { name: "rcSetDisplayColorBuffer", params: &[P::S4, P::S4], ret: 4 },
    Op { name: "rcGetDisplayColorBuffer", params: &[P::S4, P::Out], ret: 4 },
    Op { name: "rcGetColorBufferDisplay", params: &[P::S4, P::Out], ret: 4 },
    Op { name: "rcGetDisplayPose", params: &[P::S4, P::Out, P::Out, P::Out, P::Out], ret: 4 },
    Op { name: "rcSetDisplayPose", params: &[P::S4, P::S4, P::S4, P::S4, P::S4], ret: 4 },
    Op { name: "rcSetColorBufferVulkanMode", params: &[P::S4, P::S4], ret: 4 },
    Op { name: "rcReadColorBufferYUV", params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::Out, P::S4], ret: 0 },
    Op { name: "rcIsSyncSignaled", params: &[P::S8], ret: 4 },
    Op { name: "rcCreateColorBufferWithHandle", params: &[P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "rcCreateBuffer", params: &[P::S4], ret: 4 },
    Op { name: "rcCloseBuffer", params: &[P::S4], ret: 0 },
    Op { name: "rcSetColorBufferVulkanMode2", params: &[P::S4, P::S4, P::S4], ret: 4 },
    Op { name: "rcMapGpaToBufferHandle", params: &[P::S4, P::S8], ret: 4 },
    Op { name: "rcCreateBuffer2", params: &[P::S8, P::S4], ret: 4 },
    Op { name: "rcMapGpaToBufferHandle2", params: &[P::S4, P::S8, P::S8], ret: 4 },
    Op { name: "rcFlushWindowColorBufferAsyncWithFrameNumber", params: &[P::S4, P::S4], ret: 0 },
    Op { name: "rcSetTracingForPuid", params: &[P::S8, P::S4, P::S8], ret: 0 },
    Op { name: "rcMakeCurrentAsync", params: &[P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "rcComposeAsync", params: &[P::S4, P::In], ret: 0 },
    Op { name: "rcDestroySyncKHRAsync", params: &[P::S8], ret: 0 },
    Op { name: "rcComposeWithoutPost", params: &[P::S4, P::In], ret: 4 },
    Op { name: "rcComposeAsyncWithoutPost", params: &[P::S4, P::In], ret: 0 },
    Op { name: "rcCreateDisplayById", params: &[P::S4], ret: 4 },
    Op { name: "rcSetDisplayPoseDpi", params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4], ret: 4 },
    Op {
        name: "rcReadColorBufferDMA",
        params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S8, P::S4],
        ret: 4,
    },
    Op { name: "rcGetFBDisplayConfigsCount", params: &[], ret: 4 },
    Op { name: "rcGetFBDisplayConfigsParam", params: &[P::S4, P::S4], ret: 4 },
    Op { name: "rcGetFBDisplayActiveConfig", params: &[], ret: 4 },
    Op { name: "rcSetProcessMetadata", params: &[P::In, P::In, P::S4], ret: 0 },
    Op { name: "rcGetHostExtensionsString", params: &[P::S4, P::Out], ret: 4 },
];

#[allow(non_upper_case_globals, dead_code)]
pub mod rc {
    pub const rcGetRendererVersion: u32 = 10000;
    pub const rcGetEGLVersion: u32 = 10001;
    pub const rcQueryEGLString: u32 = 10002;
    pub const rcGetGLString: u32 = 10003;
    pub const rcGetNumConfigs: u32 = 10004;
    pub const rcGetConfigs: u32 = 10005;
    pub const rcChooseConfig: u32 = 10006;
    pub const rcGetFBParam: u32 = 10007;
    pub const rcCreateContext: u32 = 10008;
    pub const rcDestroyContext: u32 = 10009;
    pub const rcCreateWindowSurface: u32 = 10010;
    pub const rcDestroyWindowSurface: u32 = 10011;
    pub const rcCreateColorBuffer: u32 = 10012;
    pub const rcOpenColorBuffer: u32 = 10013;
    pub const rcCloseColorBuffer: u32 = 10014;
    pub const rcSetWindowColorBuffer: u32 = 10015;
    pub const rcFlushWindowColorBuffer: u32 = 10016;
    pub const rcMakeCurrent: u32 = 10017;
    pub const rcFBPost: u32 = 10018;
    pub const rcFBSetSwapInterval: u32 = 10019;
    pub const rcBindTexture: u32 = 10020;
    pub const rcBindRenderbuffer: u32 = 10021;
    pub const rcColorBufferCacheFlush: u32 = 10022;
    pub const rcReadColorBuffer: u32 = 10023;
    pub const rcUpdateColorBuffer: u32 = 10024;
    pub const rcOpenColorBuffer2: u32 = 10025;
    pub const rcCreateClientImage: u32 = 10026;
    pub const rcDestroyClientImage: u32 = 10027;
    pub const rcSelectChecksumHelper: u32 = 10028;
    pub const rcCreateSyncKHR: u32 = 10029;
    pub const rcClientWaitSyncKHR: u32 = 10030;
    pub const rcFlushWindowColorBufferAsync: u32 = 10031;
    pub const rcDestroySyncKHR: u32 = 10032;
    pub const rcSetPuid: u32 = 10033;
    pub const rcUpdateColorBufferDMA: u32 = 10034;
    pub const rcCreateColorBufferDMA: u32 = 10035;
    pub const rcWaitSyncKHR: u32 = 10036;
    pub const rcCompose: u32 = 10037;
    pub const rcCreateDisplay: u32 = 10038;
    pub const rcDestroyDisplay: u32 = 10039;
    pub const rcSetDisplayColorBuffer: u32 = 10040;
    pub const rcGetDisplayColorBuffer: u32 = 10041;
    pub const rcGetColorBufferDisplay: u32 = 10042;
    pub const rcGetDisplayPose: u32 = 10043;
    pub const rcSetDisplayPose: u32 = 10044;
    pub const rcSetColorBufferVulkanMode: u32 = 10045;
    pub const rcReadColorBufferYUV: u32 = 10046;
    pub const rcIsSyncSignaled: u32 = 10047;
    pub const rcCreateColorBufferWithHandle: u32 = 10048;
    pub const rcCreateBuffer: u32 = 10049;
    pub const rcCloseBuffer: u32 = 10050;
    pub const rcSetColorBufferVulkanMode2: u32 = 10051;
    pub const rcMapGpaToBufferHandle: u32 = 10052;
    pub const rcCreateBuffer2: u32 = 10053;
    pub const rcMapGpaToBufferHandle2: u32 = 10054;
    pub const rcFlushWindowColorBufferAsyncWithFrameNumber: u32 = 10055;
    pub const rcSetTracingForPuid: u32 = 10056;
    pub const rcMakeCurrentAsync: u32 = 10057;
    pub const rcComposeAsync: u32 = 10058;
    pub const rcDestroySyncKHRAsync: u32 = 10059;
    pub const rcComposeWithoutPost: u32 = 10060;
    pub const rcComposeAsyncWithoutPost: u32 = 10061;
    pub const rcCreateDisplayById: u32 = 10062;
    pub const rcSetDisplayPoseDpi: u32 = 10063;
    pub const rcReadColorBufferDMA: u32 = 10064;
    pub const rcGetFBDisplayConfigsCount: u32 = 10065;
    pub const rcGetFBDisplayConfigsParam: u32 = 10066;
    pub const rcGetFBDisplayActiveConfig: u32 = 10067;
    pub const rcSetProcessMetadata: u32 = 10068;
    pub const rcGetHostExtensionsString: u32 = 10069;
}

pub const GLES2_BASE: u32 = 2048;
pub static GLES2: [Op; 439] = [
    Op { name: "glActiveTexture", params: &[P::S4], ret: 0 },
    Op { name: "glAttachShader", params: &[P::S4, P::S4], ret: 0 },
    Op { name: "glBindAttribLocation", params: &[P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glBindBuffer", params: &[P::S4, P::S4], ret: 0 },
    Op { name: "glBindFramebuffer", params: &[P::S4, P::S4], ret: 0 },
    Op { name: "glBindRenderbuffer", params: &[P::S4, P::S4], ret: 0 },
    Op { name: "glBindTexture", params: &[P::S4, P::S4], ret: 0 },
    Op { name: "glBlendColor", params: &[P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glBlendEquation", params: &[P::S4], ret: 0 },
    Op { name: "glBlendEquationSeparate", params: &[P::S4, P::S4], ret: 0 },
    Op { name: "glBlendFunc", params: &[P::S4, P::S4], ret: 0 },
    Op { name: "glBlendFuncSeparate", params: &[P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glBufferData", params: &[P::S4, P::S4, P::In, P::S4], ret: 0 },
    Op { name: "glBufferSubData", params: &[P::S4, P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glCheckFramebufferStatus", params: &[P::S4], ret: 4 },
    Op { name: "glClear", params: &[P::S4], ret: 0 },
    Op { name: "glClearColor", params: &[P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glClearDepthf", params: &[P::S4], ret: 0 },
    Op { name: "glClearStencil", params: &[P::S4], ret: 0 },
    Op { name: "glColorMask", params: &[P::S1, P::S1, P::S1, P::S1], ret: 0 },
    Op { name: "glCompileShader", params: &[P::S4], ret: 0 },
    Op {
        name: "glCompressedTexImage2D",
        params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::In],
        ret: 0,
    },
    Op {
        name: "glCompressedTexSubImage2D",
        params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::In],
        ret: 0,
    },
    Op {
        name: "glCopyTexImage2D",
        params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4],
        ret: 0,
    },
    Op {
        name: "glCopyTexSubImage2D",
        params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4],
        ret: 0,
    },
    Op { name: "glCreateProgram", params: &[], ret: 4 },
    Op { name: "glCreateShader", params: &[P::S4], ret: 4 },
    Op { name: "glCullFace", params: &[P::S4], ret: 0 },
    Op { name: "glDeleteBuffers", params: &[P::S4, P::In], ret: 0 },
    Op { name: "glDeleteFramebuffers", params: &[P::S4, P::In], ret: 0 },
    Op { name: "glDeleteProgram", params: &[P::S4], ret: 0 },
    Op { name: "glDeleteRenderbuffers", params: &[P::S4, P::In], ret: 0 },
    Op { name: "glDeleteShader", params: &[P::S4], ret: 0 },
    Op { name: "glDeleteTextures", params: &[P::S4, P::In], ret: 0 },
    Op { name: "glDepthFunc", params: &[P::S4], ret: 0 },
    Op { name: "glDepthMask", params: &[P::S1], ret: 0 },
    Op { name: "glDepthRangef", params: &[P::S4, P::S4], ret: 0 },
    Op { name: "glDetachShader", params: &[P::S4, P::S4], ret: 0 },
    Op { name: "glDisable", params: &[P::S4], ret: 0 },
    Op { name: "glDisableVertexAttribArray", params: &[P::S4], ret: 0 },
    Op { name: "glDrawArrays", params: &[P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glDrawElements", params: &[P::S4, P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glEnable", params: &[P::S4], ret: 0 },
    Op { name: "glEnableVertexAttribArray", params: &[P::S4], ret: 0 },
    Op { name: "glFinish", params: &[], ret: 0 },
    Op { name: "glFlush", params: &[], ret: 0 },
    Op { name: "glFramebufferRenderbuffer", params: &[P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glFramebufferTexture2D", params: &[P::S4, P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glFrontFace", params: &[P::S4], ret: 0 },
    Op { name: "glGenBuffers", params: &[P::S4, P::Out], ret: 0 },
    Op { name: "glGenerateMipmap", params: &[P::S4], ret: 0 },
    Op { name: "glGenFramebuffers", params: &[P::S4, P::Out], ret: 0 },
    Op { name: "glGenRenderbuffers", params: &[P::S4, P::Out], ret: 0 },
    Op { name: "glGenTextures", params: &[P::S4, P::Out], ret: 0 },
    Op { name: "glGetActiveAttrib", params: &[P::S4, P::S4, P::S4, P::Out, P::Out, P::Out, P::Out], ret: 0 },
    Op { name: "glGetActiveUniform", params: &[P::S4, P::S4, P::S4, P::Out, P::Out, P::Out, P::Out], ret: 0 },
    Op { name: "glGetAttachedShaders", params: &[P::S4, P::S4, P::Out, P::Out], ret: 0 },
    Op { name: "glGetAttribLocation", params: &[P::S4, P::In], ret: 4 },
    Op { name: "glGetBooleanv", params: &[P::S4, P::Out], ret: 0 },
    Op { name: "glGetBufferParameteriv", params: &[P::S4, P::S4, P::Out], ret: 0 },
    Op { name: "glGetError", params: &[], ret: 4 },
    Op { name: "glGetFloatv", params: &[P::S4, P::Out], ret: 0 },
    Op { name: "glGetFramebufferAttachmentParameteriv", params: &[P::S4, P::S4, P::S4, P::Out], ret: 0 },
    Op { name: "glGetIntegerv", params: &[P::S4, P::Out], ret: 0 },
    Op { name: "glGetProgramiv", params: &[P::S4, P::S4, P::Out], ret: 0 },
    Op { name: "glGetProgramInfoLog", params: &[P::S4, P::S4, P::Out, P::Out], ret: 0 },
    Op { name: "glGetRenderbufferParameteriv", params: &[P::S4, P::S4, P::Out], ret: 0 },
    Op { name: "glGetShaderiv", params: &[P::S4, P::S4, P::Out], ret: 0 },
    Op { name: "glGetShaderInfoLog", params: &[P::S4, P::S4, P::Out, P::Out], ret: 0 },
    Op { name: "glGetShaderPrecisionFormat", params: &[P::S4, P::S4, P::Out, P::Out], ret: 0 },
    Op { name: "glGetShaderSource", params: &[P::S4, P::S4, P::Out, P::Out], ret: 0 },
    Op { name: "glGetString", params: &[P::S4], ret: 4 },
    Op { name: "glGetTexParameterfv", params: &[P::S4, P::S4, P::Out], ret: 0 },
    Op { name: "glGetTexParameteriv", params: &[P::S4, P::S4, P::Out], ret: 0 },
    Op { name: "glGetUniformfv", params: &[P::S4, P::S4, P::Out], ret: 0 },
    Op { name: "glGetUniformiv", params: &[P::S4, P::S4, P::Out], ret: 0 },
    Op { name: "glGetUniformLocation", params: &[P::S4, P::In], ret: 4 },
    Op { name: "glGetVertexAttribfv", params: &[P::S4, P::S4, P::Out], ret: 0 },
    Op { name: "glGetVertexAttribiv", params: &[P::S4, P::S4, P::Out], ret: 0 },
    Op { name: "glGetVertexAttribPointerv", params: &[P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glHint", params: &[P::S4, P::S4], ret: 0 },
    Op { name: "glIsBuffer", params: &[P::S4], ret: 1 },
    Op { name: "glIsEnabled", params: &[P::S4], ret: 1 },
    Op { name: "glIsFramebuffer", params: &[P::S4], ret: 1 },
    Op { name: "glIsProgram", params: &[P::S4], ret: 1 },
    Op { name: "glIsRenderbuffer", params: &[P::S4], ret: 1 },
    Op { name: "glIsShader", params: &[P::S4], ret: 1 },
    Op { name: "glIsTexture", params: &[P::S4], ret: 1 },
    Op { name: "glLineWidth", params: &[P::S4], ret: 0 },
    Op { name: "glLinkProgram", params: &[P::S4], ret: 0 },
    Op { name: "glPixelStorei", params: &[P::S4, P::S4], ret: 0 },
    Op { name: "glPolygonOffset", params: &[P::S4, P::S4], ret: 0 },
    Op { name: "glReadPixels", params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::Out], ret: 0 },
    Op { name: "glReleaseShaderCompiler", params: &[], ret: 0 },
    Op { name: "glRenderbufferStorage", params: &[P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glSampleCoverage", params: &[P::S4, P::S1], ret: 0 },
    Op { name: "glScissor", params: &[P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glShaderBinary", params: &[P::S4, P::In, P::S4, P::In, P::S4], ret: 0 },
    Op { name: "glShaderSource", params: &[P::S4, P::S4, P::In, P::In], ret: 0 },
    Op { name: "glStencilFunc", params: &[P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glStencilFuncSeparate", params: &[P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glStencilMask", params: &[P::S4], ret: 0 },
    Op { name: "glStencilMaskSeparate", params: &[P::S4, P::S4], ret: 0 },
    Op { name: "glStencilOp", params: &[P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glStencilOpSeparate", params: &[P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op {
        name: "glTexImage2D",
        params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::In],
        ret: 0,
    },
    Op { name: "glTexParameterf", params: &[P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glTexParameterfv", params: &[P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glTexParameteri", params: &[P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glTexParameteriv", params: &[P::S4, P::S4, P::In], ret: 0 },
    Op {
        name: "glTexSubImage2D",
        params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::In],
        ret: 0,
    },
    Op { name: "glUniform1f", params: &[P::S4, P::S4], ret: 0 },
    Op { name: "glUniform1fv", params: &[P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glUniform1i", params: &[P::S4, P::S4], ret: 0 },
    Op { name: "glUniform1iv", params: &[P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glUniform2f", params: &[P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glUniform2fv", params: &[P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glUniform2i", params: &[P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glUniform2iv", params: &[P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glUniform3f", params: &[P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glUniform3fv", params: &[P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glUniform3i", params: &[P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glUniform3iv", params: &[P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glUniform4f", params: &[P::S4, P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glUniform4fv", params: &[P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glUniform4i", params: &[P::S4, P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glUniform4iv", params: &[P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glUniformMatrix2fv", params: &[P::S4, P::S4, P::S1, P::In], ret: 0 },
    Op { name: "glUniformMatrix3fv", params: &[P::S4, P::S4, P::S1, P::In], ret: 0 },
    Op { name: "glUniformMatrix4fv", params: &[P::S4, P::S4, P::S1, P::In], ret: 0 },
    Op { name: "glUseProgram", params: &[P::S4], ret: 0 },
    Op { name: "glValidateProgram", params: &[P::S4], ret: 0 },
    Op { name: "glVertexAttrib1f", params: &[P::S4, P::S4], ret: 0 },
    Op { name: "glVertexAttrib1fv", params: &[P::S4, P::In], ret: 0 },
    Op { name: "glVertexAttrib2f", params: &[P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glVertexAttrib2fv", params: &[P::S4, P::In], ret: 0 },
    Op { name: "glVertexAttrib3f", params: &[P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glVertexAttrib3fv", params: &[P::S4, P::In], ret: 0 },
    Op { name: "glVertexAttrib4f", params: &[P::S4, P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glVertexAttrib4fv", params: &[P::S4, P::In], ret: 0 },
    Op { name: "glVertexAttribPointer", params: &[P::S4, P::S4, P::S4, P::S1, P::S4, P::In], ret: 0 },
    Op { name: "glViewport", params: &[P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glEGLImageTargetTexture2DOES", params: &[P::S4, P::S4], ret: 0 },
    Op { name: "glEGLImageTargetRenderbufferStorageOES", params: &[P::S4, P::S4], ret: 0 },
    Op { name: "glGetProgramBinaryOES", params: &[P::S4, P::S4, P::In, P::In, P::In], ret: 0 },
    Op { name: "glProgramBinaryOES", params: &[P::S4, P::S4, P::In, P::S4], ret: 0 },
    Op { name: "glMapBufferOES", params: &[P::S4, P::S4], ret: 4 },
    Op { name: "glUnmapBufferOES", params: &[P::S4], ret: 1 },
    Op {
        name: "glTexImage3DOES",
        params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::In],
        ret: 0,
    },
    Op {
        name: "glTexSubImage3DOES",
        params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::In],
        ret: 0,
    },
    Op {
        name: "glCopyTexSubImage3DOES",
        params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4],
        ret: 0,
    },
    Op {
        name: "glCompressedTexImage3DOES",
        params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::In],
        ret: 0,
    },
    Op {
        name: "glCompressedTexSubImage3DOES",
        params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::In],
        ret: 0,
    },
    Op { name: "glFramebufferTexture3DOES", params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glBindVertexArrayOES", params: &[P::S4], ret: 0 },
    Op { name: "glDeleteVertexArraysOES", params: &[P::S4, P::In], ret: 0 },
    Op { name: "glGenVertexArraysOES", params: &[P::S4, P::Out], ret: 0 },
    Op { name: "glIsVertexArrayOES", params: &[P::S4], ret: 1 },
    Op { name: "glDiscardFramebufferEXT", params: &[P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glMultiDrawArraysEXT", params: &[P::S4, P::In, P::In, P::S4], ret: 0 },
    Op { name: "glMultiDrawElementsEXT", params: &[P::S4, P::In, P::S4, P::In, P::S4], ret: 0 },
    Op { name: "glGetPerfMonitorGroupsAMD", params: &[P::In, P::S4, P::In], ret: 0 },
    Op { name: "glGetPerfMonitorCountersAMD", params: &[P::S4, P::In, P::In, P::S4, P::In], ret: 0 },
    Op { name: "glGetPerfMonitorGroupStringAMD", params: &[P::S4, P::S4, P::In, P::In], ret: 0 },
    Op { name: "glGetPerfMonitorCounterStringAMD", params: &[P::S4, P::S4, P::S4, P::In, P::In], ret: 0 },
    Op { name: "glGetPerfMonitorCounterInfoAMD", params: &[P::S4, P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glGenPerfMonitorsAMD", params: &[P::S4, P::In], ret: 0 },
    Op { name: "glDeletePerfMonitorsAMD", params: &[P::S4, P::In], ret: 0 },
    Op { name: "glSelectPerfMonitorCountersAMD", params: &[P::S4, P::S1, P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glBeginPerfMonitorAMD", params: &[P::S4], ret: 0 },
    Op { name: "glEndPerfMonitorAMD", params: &[P::S4], ret: 0 },
    Op { name: "glGetPerfMonitorCounterDataAMD", params: &[P::S4, P::S4, P::S4, P::In, P::In], ret: 0 },
    Op { name: "glRenderbufferStorageMultisampleIMG", params: &[P::S4, P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op {
        name: "glFramebufferTexture2DMultisampleIMG",
        params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4],
        ret: 0,
    },
    Op { name: "glDeleteFencesNV", params: &[P::S4, P::In], ret: 0 },
    Op { name: "glGenFencesNV", params: &[P::S4, P::In], ret: 0 },
    Op { name: "glIsFenceNV", params: &[P::S4], ret: 1 },
    Op { name: "glTestFenceNV", params: &[P::S4], ret: 1 },
    Op { name: "glGetFenceivNV", params: &[P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glFinishFenceNV", params: &[P::S4], ret: 0 },
    Op { name: "glSetFenceNV", params: &[P::S4, P::S4], ret: 0 },
    Op { name: "glCoverageMaskNV", params: &[P::S1], ret: 0 },
    Op { name: "glCoverageOperationNV", params: &[P::S4], ret: 0 },
    Op { name: "glGetDriverControlsQCOM", params: &[P::In, P::S4, P::In], ret: 0 },
    Op { name: "glGetDriverControlStringQCOM", params: &[P::S4, P::S4, P::In, P::In], ret: 0 },
    Op { name: "glEnableDriverControlQCOM", params: &[P::S4], ret: 0 },
    Op { name: "glDisableDriverControlQCOM", params: &[P::S4], ret: 0 },
    Op { name: "glExtGetTexturesQCOM", params: &[P::In, P::S4, P::In], ret: 0 },
    Op { name: "glExtGetBuffersQCOM", params: &[P::In, P::S4, P::In], ret: 0 },
    Op { name: "glExtGetRenderbuffersQCOM", params: &[P::In, P::S4, P::In], ret: 0 },
    Op { name: "glExtGetFramebuffersQCOM", params: &[P::In, P::S4, P::In], ret: 0 },
    Op { name: "glExtGetTexLevelParameterivQCOM", params: &[P::S4, P::S4, P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glExtTexObjectStateOverrideiQCOM", params: &[P::S4, P::S4, P::S4], ret: 0 },
    Op {
        name: "glExtGetTexSubImageQCOM",
        params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::In],
        ret: 0,
    },
    Op { name: "glExtGetBufferPointervQCOM", params: &[P::S4, P::In], ret: 0 },
    Op { name: "glExtGetShadersQCOM", params: &[P::In, P::S4, P::In], ret: 0 },
    Op { name: "glExtGetProgramsQCOM", params: &[P::In, P::S4, P::In], ret: 0 },
    Op { name: "glExtIsProgramBinaryQCOM", params: &[P::S4], ret: 1 },
    Op { name: "glExtGetProgramBinarySourceQCOM", params: &[P::S4, P::S4, P::In, P::In], ret: 0 },
    Op { name: "glStartTilingQCOM", params: &[P::S4, P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glEndTilingQCOM", params: &[P::S4], ret: 0 },
    Op {
        name: "glVertexAttribPointerData",
        params: &[P::S4, P::S4, P::S4, P::S1, P::S4, P::In, P::S4],
        ret: 0,
    },
    Op { name: "glVertexAttribPointerOffset", params: &[P::S4, P::S4, P::S4, P::S1, P::S4, P::S4], ret: 0 },
    Op { name: "glDrawElementsOffset", params: &[P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glDrawElementsData", params: &[P::S4, P::S4, P::S4, P::In, P::S4], ret: 0 },
    Op { name: "glGetCompressedTextureFormats", params: &[P::S4, P::Out], ret: 0 },
    Op { name: "glShaderString", params: &[P::S4, P::In, P::S4], ret: 0 },
    Op { name: "glFinishRoundTrip", params: &[], ret: 4 },
    Op { name: "glGenVertexArrays", params: &[P::S4, P::Out], ret: 0 },
    Op { name: "glBindVertexArray", params: &[P::S4], ret: 0 },
    Op { name: "glDeleteVertexArrays", params: &[P::S4, P::In], ret: 0 },
    Op { name: "glIsVertexArray", params: &[P::S4], ret: 1 },
    Op { name: "glMapBufferRange", params: &[P::S4, P::S4, P::S4, P::S4], ret: 4 },
    Op { name: "glUnmapBuffer", params: &[P::S4], ret: 1 },
    Op { name: "glFlushMappedBufferRange", params: &[P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glMapBufferRangeAEMU", params: &[P::S4, P::S4, P::S4, P::S4, P::Out], ret: 0 },
    Op { name: "glUnmapBufferAEMU", params: &[P::S4, P::S4, P::S4, P::S4, P::In, P::Out], ret: 0 },
    Op { name: "glFlushMappedBufferRangeAEMU", params: &[P::S4, P::S4, P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glReadPixelsOffsetAEMU", params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op {
        name: "glCompressedTexImage2DOffsetAEMU",
        params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4],
        ret: 0,
    },
    Op {
        name: "glCompressedTexSubImage2DOffsetAEMU",
        params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4],
        ret: 0,
    },
    Op {
        name: "glTexImage2DOffsetAEMU",
        params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4],
        ret: 0,
    },
    Op {
        name: "glTexSubImage2DOffsetAEMU",
        params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4],
        ret: 0,
    },
    Op { name: "glBindBufferRange", params: &[P::S4, P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glBindBufferBase", params: &[P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glCopyBufferSubData", params: &[P::S4, P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glClearBufferiv", params: &[P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glClearBufferuiv", params: &[P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glClearBufferfv", params: &[P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glClearBufferfi", params: &[P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glGetBufferParameteri64v", params: &[P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glGetBufferPointerv", params: &[P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glUniformBlockBinding", params: &[P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glGetUniformBlockIndex", params: &[P::S4, P::In], ret: 4 },
    Op { name: "glGetUniformIndices", params: &[P::S4, P::S4, P::In, P::In], ret: 0 },
    Op { name: "glGetUniformIndicesAEMU", params: &[P::S4, P::S4, P::In, P::S4, P::Out], ret: 0 },
    Op { name: "glGetActiveUniformBlockiv", params: &[P::S4, P::S4, P::S4, P::Out], ret: 0 },
    Op { name: "glGetActiveUniformBlockName", params: &[P::S4, P::S4, P::S4, P::Out, P::Out], ret: 0 },
    Op { name: "glUniform1ui", params: &[P::S4, P::S4], ret: 0 },
    Op { name: "glUniform2ui", params: &[P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glUniform3ui", params: &[P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glUniform4ui", params: &[P::S4, P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glUniform1uiv", params: &[P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glUniform2uiv", params: &[P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glUniform3uiv", params: &[P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glUniform4uiv", params: &[P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glUniformMatrix2x3fv", params: &[P::S4, P::S4, P::S1, P::In], ret: 0 },
    Op { name: "glUniformMatrix3x2fv", params: &[P::S4, P::S4, P::S1, P::In], ret: 0 },
    Op { name: "glUniformMatrix2x4fv", params: &[P::S4, P::S4, P::S1, P::In], ret: 0 },
    Op { name: "glUniformMatrix4x2fv", params: &[P::S4, P::S4, P::S1, P::In], ret: 0 },
    Op { name: "glUniformMatrix3x4fv", params: &[P::S4, P::S4, P::S1, P::In], ret: 0 },
    Op { name: "glUniformMatrix4x3fv", params: &[P::S4, P::S4, P::S1, P::In], ret: 0 },
    Op { name: "glGetUniformuiv", params: &[P::S4, P::S4, P::Out], ret: 0 },
    Op { name: "glGetActiveUniformsiv", params: &[P::S4, P::S4, P::In, P::S4, P::Out], ret: 0 },
    Op { name: "glVertexAttribI4i", params: &[P::S4, P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glVertexAttribI4ui", params: &[P::S4, P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glVertexAttribI4iv", params: &[P::S4, P::In], ret: 0 },
    Op { name: "glVertexAttribI4uiv", params: &[P::S4, P::In], ret: 0 },
    Op { name: "glVertexAttribIPointer", params: &[P::S4, P::S4, P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glVertexAttribIPointerOffsetAEMU", params: &[P::S4, P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op {
        name: "glVertexAttribIPointerDataAEMU",
        params: &[P::S4, P::S4, P::S4, P::S4, P::In, P::S4],
        ret: 0,
    },
    Op { name: "glGetVertexAttribIiv", params: &[P::S4, P::S4, P::Out], ret: 0 },
    Op { name: "glGetVertexAttribIuiv", params: &[P::S4, P::S4, P::Out], ret: 0 },
    Op { name: "glVertexAttribDivisor", params: &[P::S4, P::S4], ret: 0 },
    Op { name: "glDrawArraysInstanced", params: &[P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glDrawElementsInstanced", params: &[P::S4, P::S4, P::S4, P::In, P::S4], ret: 0 },
    Op {
        name: "glDrawElementsInstancedDataAEMU",
        params: &[P::S4, P::S4, P::S4, P::In, P::S4, P::S4],
        ret: 0,
    },
    Op { name: "glDrawElementsInstancedOffsetAEMU", params: &[P::S4, P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glDrawRangeElements", params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::In], ret: 0 },
    Op {
        name: "glDrawRangeElementsDataAEMU",
        params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::In, P::S4],
        ret: 0,
    },
    Op { name: "glDrawRangeElementsOffsetAEMU", params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glFenceSync", params: &[P::S4, P::S4], ret: 8 },
    Op { name: "glClientWaitSync", params: &[P::S8, P::S4, P::S8], ret: 4 },
    Op { name: "glWaitSync", params: &[P::S8, P::S4, P::S8], ret: 0 },
    Op { name: "glDeleteSync", params: &[P::S8], ret: 0 },
    Op { name: "glIsSync", params: &[P::S8], ret: 1 },
    Op { name: "glGetSynciv", params: &[P::S8, P::S4, P::S4, P::In, P::In], ret: 0 },
    Op { name: "glFenceSyncAEMU", params: &[P::S4, P::S4], ret: 8 },
    Op { name: "glClientWaitSyncAEMU", params: &[P::S8, P::S4, P::S8], ret: 4 },
    Op { name: "glWaitSyncAEMU", params: &[P::S8, P::S4, P::S8], ret: 0 },
    Op { name: "glDeleteSyncAEMU", params: &[P::S8], ret: 0 },
    Op { name: "glIsSyncAEMU", params: &[P::S8], ret: 1 },
    Op { name: "glGetSyncivAEMU", params: &[P::S8, P::S4, P::S4, P::Out, P::Out], ret: 0 },
    Op { name: "glDrawBuffers", params: &[P::S4, P::In], ret: 0 },
    Op { name: "glReadBuffer", params: &[P::S4], ret: 0 },
    Op {
        name: "glBlitFramebuffer",
        params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4],
        ret: 0,
    },
    Op { name: "glInvalidateFramebuffer", params: &[P::S4, P::S4, P::In], ret: 0 },
    Op {
        name: "glInvalidateSubFramebuffer",
        params: &[P::S4, P::S4, P::In, P::S4, P::S4, P::S4, P::S4],
        ret: 0,
    },
    Op { name: "glFramebufferTextureLayer", params: &[P::S4, P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glRenderbufferStorageMultisample", params: &[P::S4, P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glTexStorage2D", params: &[P::S4, P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glGetInternalformativ", params: &[P::S4, P::S4, P::S4, P::S4, P::Out], ret: 0 },
    Op { name: "glBeginTransformFeedback", params: &[P::S4], ret: 0 },
    Op { name: "glEndTransformFeedback", params: &[], ret: 0 },
    Op { name: "glGenTransformFeedbacks", params: &[P::S4, P::Out], ret: 0 },
    Op { name: "glDeleteTransformFeedbacks", params: &[P::S4, P::In], ret: 0 },
    Op { name: "glBindTransformFeedback", params: &[P::S4, P::S4], ret: 0 },
    Op { name: "glPauseTransformFeedback", params: &[], ret: 0 },
    Op { name: "glResumeTransformFeedback", params: &[], ret: 0 },
    Op { name: "glIsTransformFeedback", params: &[P::S4], ret: 1 },
    Op { name: "glTransformFeedbackVaryings", params: &[P::S4, P::S4, P::In, P::S4], ret: 0 },
    Op { name: "glTransformFeedbackVaryingsAEMU", params: &[P::S4, P::S4, P::In, P::S4, P::S4], ret: 0 },
    Op {
        name: "glGetTransformFeedbackVarying",
        params: &[P::S4, P::S4, P::S4, P::Out, P::Out, P::Out, P::Out],
        ret: 0,
    },
    Op { name: "glGenSamplers", params: &[P::S4, P::Out], ret: 0 },
    Op { name: "glDeleteSamplers", params: &[P::S4, P::In], ret: 0 },
    Op { name: "glBindSampler", params: &[P::S4, P::S4], ret: 0 },
    Op { name: "glSamplerParameterf", params: &[P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glSamplerParameteri", params: &[P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glSamplerParameterfv", params: &[P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glSamplerParameteriv", params: &[P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glGetSamplerParameterfv", params: &[P::S4, P::S4, P::Out], ret: 0 },
    Op { name: "glGetSamplerParameteriv", params: &[P::S4, P::S4, P::Out], ret: 0 },
    Op { name: "glIsSampler", params: &[P::S4], ret: 1 },
    Op { name: "glGenQueries", params: &[P::S4, P::Out], ret: 0 },
    Op { name: "glDeleteQueries", params: &[P::S4, P::In], ret: 0 },
    Op { name: "glBeginQuery", params: &[P::S4, P::S4], ret: 0 },
    Op { name: "glEndQuery", params: &[P::S4], ret: 0 },
    Op { name: "glGetQueryiv", params: &[P::S4, P::S4, P::Out], ret: 0 },
    Op { name: "glGetQueryObjectuiv", params: &[P::S4, P::S4, P::Out], ret: 0 },
    Op { name: "glIsQuery", params: &[P::S4], ret: 1 },
    Op { name: "glProgramParameteri", params: &[P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glProgramBinary", params: &[P::S4, P::S4, P::In, P::S4], ret: 0 },
    Op { name: "glGetProgramBinary", params: &[P::S4, P::S4, P::Out, P::Out, P::Out], ret: 0 },
    Op { name: "glGetFragDataLocation", params: &[P::S4, P::In], ret: 4 },
    Op { name: "glGetInteger64v", params: &[P::S4, P::Out], ret: 0 },
    Op { name: "glGetIntegeri_v", params: &[P::S4, P::S4, P::Out], ret: 0 },
    Op { name: "glGetInteger64i_v", params: &[P::S4, P::S4, P::Out], ret: 0 },
    Op {
        name: "glTexImage3D",
        params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::In],
        ret: 0,
    },
    Op {
        name: "glTexImage3DOffsetAEMU",
        params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4],
        ret: 0,
    },
    Op { name: "glTexStorage3D", params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op {
        name: "glTexSubImage3D",
        params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::In],
        ret: 0,
    },
    Op {
        name: "glTexSubImage3DOffsetAEMU",
        params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4],
        ret: 0,
    },
    Op {
        name: "glCompressedTexImage3D",
        params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::In],
        ret: 0,
    },
    Op {
        name: "glCompressedTexImage3DOffsetAEMU",
        params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4],
        ret: 0,
    },
    Op {
        name: "glCompressedTexSubImage3D",
        params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::In],
        ret: 0,
    },
    Op {
        name: "glCompressedTexSubImage3DOffsetAEMU",
        params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4],
        ret: 0,
    },
    Op {
        name: "glCopyTexSubImage3D",
        params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4],
        ret: 0,
    },
    Op { name: "glGetStringi", params: &[P::S4, P::S4], ret: 4 },
    Op { name: "glGetBooleani_v", params: &[P::S4, P::S4, P::Out], ret: 0 },
    Op { name: "glMemoryBarrier", params: &[P::S4], ret: 0 },
    Op { name: "glMemoryBarrierByRegion", params: &[P::S4], ret: 0 },
    Op { name: "glGenProgramPipelines", params: &[P::S4, P::Out], ret: 0 },
    Op { name: "glDeleteProgramPipelines", params: &[P::S4, P::In], ret: 0 },
    Op { name: "glBindProgramPipeline", params: &[P::S4], ret: 0 },
    Op { name: "glGetProgramPipelineiv", params: &[P::S4, P::S4, P::Out], ret: 0 },
    Op { name: "glGetProgramPipelineInfoLog", params: &[P::S4, P::S4, P::Out, P::Out], ret: 0 },
    Op { name: "glValidateProgramPipeline", params: &[P::S4], ret: 0 },
    Op { name: "glIsProgramPipeline", params: &[P::S4], ret: 1 },
    Op { name: "glUseProgramStages", params: &[P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glActiveShaderProgram", params: &[P::S4, P::S4], ret: 0 },
    Op { name: "glCreateShaderProgramv", params: &[P::S4, P::S4, P::In], ret: 4 },
    Op { name: "glCreateShaderProgramvAEMU", params: &[P::S4, P::S4, P::In, P::S4], ret: 4 },
    Op { name: "glProgramUniform1f", params: &[P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glProgramUniform2f", params: &[P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glProgramUniform3f", params: &[P::S4, P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glProgramUniform4f", params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glProgramUniform1i", params: &[P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glProgramUniform2i", params: &[P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glProgramUniform3i", params: &[P::S4, P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glProgramUniform4i", params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glProgramUniform1ui", params: &[P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glProgramUniform2ui", params: &[P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glProgramUniform3ui", params: &[P::S4, P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glProgramUniform4ui", params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glProgramUniform1fv", params: &[P::S4, P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glProgramUniform2fv", params: &[P::S4, P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glProgramUniform3fv", params: &[P::S4, P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glProgramUniform4fv", params: &[P::S4, P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glProgramUniform1iv", params: &[P::S4, P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glProgramUniform2iv", params: &[P::S4, P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glProgramUniform3iv", params: &[P::S4, P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glProgramUniform4iv", params: &[P::S4, P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glProgramUniform1uiv", params: &[P::S4, P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glProgramUniform2uiv", params: &[P::S4, P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glProgramUniform3uiv", params: &[P::S4, P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glProgramUniform4uiv", params: &[P::S4, P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glProgramUniformMatrix2fv", params: &[P::S4, P::S4, P::S4, P::S1, P::In], ret: 0 },
    Op { name: "glProgramUniformMatrix3fv", params: &[P::S4, P::S4, P::S4, P::S1, P::In], ret: 0 },
    Op { name: "glProgramUniformMatrix4fv", params: &[P::S4, P::S4, P::S4, P::S1, P::In], ret: 0 },
    Op { name: "glProgramUniformMatrix2x3fv", params: &[P::S4, P::S4, P::S4, P::S1, P::In], ret: 0 },
    Op { name: "glProgramUniformMatrix3x2fv", params: &[P::S4, P::S4, P::S4, P::S1, P::In], ret: 0 },
    Op { name: "glProgramUniformMatrix2x4fv", params: &[P::S4, P::S4, P::S4, P::S1, P::In], ret: 0 },
    Op { name: "glProgramUniformMatrix4x2fv", params: &[P::S4, P::S4, P::S4, P::S1, P::In], ret: 0 },
    Op { name: "glProgramUniformMatrix3x4fv", params: &[P::S4, P::S4, P::S4, P::S1, P::In], ret: 0 },
    Op { name: "glProgramUniformMatrix4x3fv", params: &[P::S4, P::S4, P::S4, P::S1, P::In], ret: 0 },
    Op { name: "glGetProgramInterfaceiv", params: &[P::S4, P::S4, P::S4, P::Out], ret: 0 },
    Op {
        name: "glGetProgramResourceiv",
        params: &[P::S4, P::S4, P::S4, P::S4, P::In, P::S4, P::Out, P::Out],
        ret: 0,
    },
    Op { name: "glGetProgramResourceIndex", params: &[P::S4, P::S4, P::In], ret: 4 },
    Op { name: "glGetProgramResourceLocation", params: &[P::S4, P::S4, P::In], ret: 4 },
    Op { name: "glGetProgramResourceName", params: &[P::S4, P::S4, P::S4, P::S4, P::Out, P::Out], ret: 0 },
    Op { name: "glBindImageTexture", params: &[P::S4, P::S4, P::S4, P::S1, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glDispatchCompute", params: &[P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glDispatchComputeIndirect", params: &[P::S4], ret: 0 },
    Op { name: "glBindVertexBuffer", params: &[P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glVertexAttribBinding", params: &[P::S4, P::S4], ret: 0 },
    Op { name: "glVertexAttribFormat", params: &[P::S4, P::S4, P::S4, P::S1, P::S4], ret: 0 },
    Op { name: "glVertexAttribIFormat", params: &[P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glVertexBindingDivisor", params: &[P::S4, P::S4], ret: 0 },
    Op { name: "glDrawArraysIndirect", params: &[P::S4, P::In], ret: 0 },
    Op { name: "glDrawArraysIndirectDataAEMU", params: &[P::S4, P::In, P::S4], ret: 0 },
    Op { name: "glDrawArraysIndirectOffsetAEMU", params: &[P::S4, P::S4], ret: 0 },
    Op { name: "glDrawElementsIndirect", params: &[P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glDrawElementsIndirectDataAEMU", params: &[P::S4, P::S4, P::In, P::S4], ret: 0 },
    Op { name: "glDrawElementsIndirectOffsetAEMU", params: &[P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glTexStorage2DMultisample", params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S1], ret: 0 },
    Op { name: "glSampleMaski", params: &[P::S4, P::S4], ret: 0 },
    Op { name: "glGetMultisamplefv", params: &[P::S4, P::S4, P::Out], ret: 0 },
    Op { name: "glFramebufferParameteri", params: &[P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glGetFramebufferParameteriv", params: &[P::S4, P::S4, P::Out], ret: 0 },
    Op { name: "glGetTexLevelParameterfv", params: &[P::S4, P::S4, P::S4, P::Out], ret: 0 },
    Op { name: "glGetTexLevelParameteriv", params: &[P::S4, P::S4, P::S4, P::Out], ret: 0 },
    Op { name: "glMapBufferRangeDMA", params: &[P::S4, P::S4, P::S4, P::S4, P::S8], ret: 0 },
    Op { name: "glUnmapBufferDMA", params: &[P::S4, P::S4, P::S4, P::S4, P::S8, P::Out], ret: 0 },
    Op { name: "glMapBufferRangeDirect", params: &[P::S4, P::S4, P::S4, P::S4, P::S8], ret: 8 },
    Op { name: "glUnmapBufferDirect", params: &[P::S4, P::S4, P::S4, P::S4, P::S8, P::S8, P::Out], ret: 0 },
    Op { name: "glFlushMappedBufferRangeDirect", params: &[P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glGetGraphicsResetStatusEXT", params: &[], ret: 4 },
    Op {
        name: "glReadnPixelsEXT",
        params: &[P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::S4, P::Out],
        ret: 0,
    },
    Op { name: "glGetnUniformfvEXT", params: &[P::S4, P::S4, P::S4, P::Out], ret: 0 },
    Op { name: "glGetnUniformivEXT", params: &[P::S4, P::S4, P::S4, P::Out], ret: 0 },
    Op { name: "glDrawArraysNullAEMU", params: &[P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glDrawElementsNullAEMU", params: &[P::S4, P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glDrawElementsOffsetNullAEMU", params: &[P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glDrawElementsDataNullAEMU", params: &[P::S4, P::S4, P::S4, P::In, P::S4], ret: 0 },
    Op { name: "glUnmapBufferAsyncAEMU", params: &[P::S4, P::S4, P::S4, P::S4, P::In, P::In], ret: 0 },
    Op { name: "glFlushMappedBufferRangeAEMU2", params: &[P::S4, P::S4, P::S4, P::S4, P::In], ret: 0 },
    Op { name: "glBufferDataSyncAEMU", params: &[P::S4, P::S4, P::In, P::S4], ret: 1 },
    Op { name: "glTexBufferOES", params: &[P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glTexBufferRangeOES", params: &[P::S4, P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glTexBufferEXT", params: &[P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glTexBufferRangeEXT", params: &[P::S4, P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glEnableiEXT", params: &[P::S4, P::S4], ret: 0 },
    Op { name: "glDisableiEXT", params: &[P::S4, P::S4], ret: 0 },
    Op { name: "glBlendEquationiEXT", params: &[P::S4, P::S4], ret: 0 },
    Op { name: "glBlendEquationSeparateiEXT", params: &[P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glBlendFunciEXT", params: &[P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glBlendFuncSeparateiEXT", params: &[P::S4, P::S4, P::S4, P::S4, P::S4], ret: 0 },
    Op { name: "glColorMaskiEXT", params: &[P::S4, P::S1, P::S1, P::S1, P::S1], ret: 0 },
    Op { name: "glIsEnablediEXT", params: &[P::S4, P::S4], ret: 1 },
];

#[allow(non_upper_case_globals, dead_code)]
pub mod gles2 {
    pub const glActiveTexture: u32 = 2048;
    pub const glAttachShader: u32 = 2049;
    pub const glBindAttribLocation: u32 = 2050;
    pub const glBindBuffer: u32 = 2051;
    pub const glBindFramebuffer: u32 = 2052;
    pub const glBindRenderbuffer: u32 = 2053;
    pub const glBindTexture: u32 = 2054;
    pub const glBlendColor: u32 = 2055;
    pub const glBlendEquation: u32 = 2056;
    pub const glBlendEquationSeparate: u32 = 2057;
    pub const glBlendFunc: u32 = 2058;
    pub const glBlendFuncSeparate: u32 = 2059;
    pub const glBufferData: u32 = 2060;
    pub const glBufferSubData: u32 = 2061;
    pub const glCheckFramebufferStatus: u32 = 2062;
    pub const glClear: u32 = 2063;
    pub const glClearColor: u32 = 2064;
    pub const glClearDepthf: u32 = 2065;
    pub const glClearStencil: u32 = 2066;
    pub const glColorMask: u32 = 2067;
    pub const glCompileShader: u32 = 2068;
    pub const glCompressedTexImage2D: u32 = 2069;
    pub const glCompressedTexSubImage2D: u32 = 2070;
    pub const glCopyTexImage2D: u32 = 2071;
    pub const glCopyTexSubImage2D: u32 = 2072;
    pub const glCreateProgram: u32 = 2073;
    pub const glCreateShader: u32 = 2074;
    pub const glCullFace: u32 = 2075;
    pub const glDeleteBuffers: u32 = 2076;
    pub const glDeleteFramebuffers: u32 = 2077;
    pub const glDeleteProgram: u32 = 2078;
    pub const glDeleteRenderbuffers: u32 = 2079;
    pub const glDeleteShader: u32 = 2080;
    pub const glDeleteTextures: u32 = 2081;
    pub const glDepthFunc: u32 = 2082;
    pub const glDepthMask: u32 = 2083;
    pub const glDepthRangef: u32 = 2084;
    pub const glDetachShader: u32 = 2085;
    pub const glDisable: u32 = 2086;
    pub const glDisableVertexAttribArray: u32 = 2087;
    pub const glDrawArrays: u32 = 2088;
    pub const glDrawElements: u32 = 2089;
    pub const glEnable: u32 = 2090;
    pub const glEnableVertexAttribArray: u32 = 2091;
    pub const glFinish: u32 = 2092;
    pub const glFlush: u32 = 2093;
    pub const glFramebufferRenderbuffer: u32 = 2094;
    pub const glFramebufferTexture2D: u32 = 2095;
    pub const glFrontFace: u32 = 2096;
    pub const glGenBuffers: u32 = 2097;
    pub const glGenerateMipmap: u32 = 2098;
    pub const glGenFramebuffers: u32 = 2099;
    pub const glGenRenderbuffers: u32 = 2100;
    pub const glGenTextures: u32 = 2101;
    pub const glGetActiveAttrib: u32 = 2102;
    pub const glGetActiveUniform: u32 = 2103;
    pub const glGetAttachedShaders: u32 = 2104;
    pub const glGetAttribLocation: u32 = 2105;
    pub const glGetBooleanv: u32 = 2106;
    pub const glGetBufferParameteriv: u32 = 2107;
    pub const glGetError: u32 = 2108;
    pub const glGetFloatv: u32 = 2109;
    pub const glGetFramebufferAttachmentParameteriv: u32 = 2110;
    pub const glGetIntegerv: u32 = 2111;
    pub const glGetProgramiv: u32 = 2112;
    pub const glGetProgramInfoLog: u32 = 2113;
    pub const glGetRenderbufferParameteriv: u32 = 2114;
    pub const glGetShaderiv: u32 = 2115;
    pub const glGetShaderInfoLog: u32 = 2116;
    pub const glGetShaderPrecisionFormat: u32 = 2117;
    pub const glGetShaderSource: u32 = 2118;
    pub const glGetString: u32 = 2119;
    pub const glGetTexParameterfv: u32 = 2120;
    pub const glGetTexParameteriv: u32 = 2121;
    pub const glGetUniformfv: u32 = 2122;
    pub const glGetUniformiv: u32 = 2123;
    pub const glGetUniformLocation: u32 = 2124;
    pub const glGetVertexAttribfv: u32 = 2125;
    pub const glGetVertexAttribiv: u32 = 2126;
    pub const glGetVertexAttribPointerv: u32 = 2127;
    pub const glHint: u32 = 2128;
    pub const glIsBuffer: u32 = 2129;
    pub const glIsEnabled: u32 = 2130;
    pub const glIsFramebuffer: u32 = 2131;
    pub const glIsProgram: u32 = 2132;
    pub const glIsRenderbuffer: u32 = 2133;
    pub const glIsShader: u32 = 2134;
    pub const glIsTexture: u32 = 2135;
    pub const glLineWidth: u32 = 2136;
    pub const glLinkProgram: u32 = 2137;
    pub const glPixelStorei: u32 = 2138;
    pub const glPolygonOffset: u32 = 2139;
    pub const glReadPixels: u32 = 2140;
    pub const glReleaseShaderCompiler: u32 = 2141;
    pub const glRenderbufferStorage: u32 = 2142;
    pub const glSampleCoverage: u32 = 2143;
    pub const glScissor: u32 = 2144;
    pub const glShaderBinary: u32 = 2145;
    pub const glShaderSource: u32 = 2146;
    pub const glStencilFunc: u32 = 2147;
    pub const glStencilFuncSeparate: u32 = 2148;
    pub const glStencilMask: u32 = 2149;
    pub const glStencilMaskSeparate: u32 = 2150;
    pub const glStencilOp: u32 = 2151;
    pub const glStencilOpSeparate: u32 = 2152;
    pub const glTexImage2D: u32 = 2153;
    pub const glTexParameterf: u32 = 2154;
    pub const glTexParameterfv: u32 = 2155;
    pub const glTexParameteri: u32 = 2156;
    pub const glTexParameteriv: u32 = 2157;
    pub const glTexSubImage2D: u32 = 2158;
    pub const glUniform1f: u32 = 2159;
    pub const glUniform1fv: u32 = 2160;
    pub const glUniform1i: u32 = 2161;
    pub const glUniform1iv: u32 = 2162;
    pub const glUniform2f: u32 = 2163;
    pub const glUniform2fv: u32 = 2164;
    pub const glUniform2i: u32 = 2165;
    pub const glUniform2iv: u32 = 2166;
    pub const glUniform3f: u32 = 2167;
    pub const glUniform3fv: u32 = 2168;
    pub const glUniform3i: u32 = 2169;
    pub const glUniform3iv: u32 = 2170;
    pub const glUniform4f: u32 = 2171;
    pub const glUniform4fv: u32 = 2172;
    pub const glUniform4i: u32 = 2173;
    pub const glUniform4iv: u32 = 2174;
    pub const glUniformMatrix2fv: u32 = 2175;
    pub const glUniformMatrix3fv: u32 = 2176;
    pub const glUniformMatrix4fv: u32 = 2177;
    pub const glUseProgram: u32 = 2178;
    pub const glValidateProgram: u32 = 2179;
    pub const glVertexAttrib1f: u32 = 2180;
    pub const glVertexAttrib1fv: u32 = 2181;
    pub const glVertexAttrib2f: u32 = 2182;
    pub const glVertexAttrib2fv: u32 = 2183;
    pub const glVertexAttrib3f: u32 = 2184;
    pub const glVertexAttrib3fv: u32 = 2185;
    pub const glVertexAttrib4f: u32 = 2186;
    pub const glVertexAttrib4fv: u32 = 2187;
    pub const glVertexAttribPointer: u32 = 2188;
    pub const glViewport: u32 = 2189;
    pub const glEGLImageTargetTexture2DOES: u32 = 2190;
    pub const glEGLImageTargetRenderbufferStorageOES: u32 = 2191;
    pub const glGetProgramBinaryOES: u32 = 2192;
    pub const glProgramBinaryOES: u32 = 2193;
    pub const glMapBufferOES: u32 = 2194;
    pub const glUnmapBufferOES: u32 = 2195;
    pub const glTexImage3DOES: u32 = 2196;
    pub const glTexSubImage3DOES: u32 = 2197;
    pub const glCopyTexSubImage3DOES: u32 = 2198;
    pub const glCompressedTexImage3DOES: u32 = 2199;
    pub const glCompressedTexSubImage3DOES: u32 = 2200;
    pub const glFramebufferTexture3DOES: u32 = 2201;
    pub const glBindVertexArrayOES: u32 = 2202;
    pub const glDeleteVertexArraysOES: u32 = 2203;
    pub const glGenVertexArraysOES: u32 = 2204;
    pub const glIsVertexArrayOES: u32 = 2205;
    pub const glDiscardFramebufferEXT: u32 = 2206;
    pub const glMultiDrawArraysEXT: u32 = 2207;
    pub const glMultiDrawElementsEXT: u32 = 2208;
    pub const glGetPerfMonitorGroupsAMD: u32 = 2209;
    pub const glGetPerfMonitorCountersAMD: u32 = 2210;
    pub const glGetPerfMonitorGroupStringAMD: u32 = 2211;
    pub const glGetPerfMonitorCounterStringAMD: u32 = 2212;
    pub const glGetPerfMonitorCounterInfoAMD: u32 = 2213;
    pub const glGenPerfMonitorsAMD: u32 = 2214;
    pub const glDeletePerfMonitorsAMD: u32 = 2215;
    pub const glSelectPerfMonitorCountersAMD: u32 = 2216;
    pub const glBeginPerfMonitorAMD: u32 = 2217;
    pub const glEndPerfMonitorAMD: u32 = 2218;
    pub const glGetPerfMonitorCounterDataAMD: u32 = 2219;
    pub const glRenderbufferStorageMultisampleIMG: u32 = 2220;
    pub const glFramebufferTexture2DMultisampleIMG: u32 = 2221;
    pub const glDeleteFencesNV: u32 = 2222;
    pub const glGenFencesNV: u32 = 2223;
    pub const glIsFenceNV: u32 = 2224;
    pub const glTestFenceNV: u32 = 2225;
    pub const glGetFenceivNV: u32 = 2226;
    pub const glFinishFenceNV: u32 = 2227;
    pub const glSetFenceNV: u32 = 2228;
    pub const glCoverageMaskNV: u32 = 2229;
    pub const glCoverageOperationNV: u32 = 2230;
    pub const glGetDriverControlsQCOM: u32 = 2231;
    pub const glGetDriverControlStringQCOM: u32 = 2232;
    pub const glEnableDriverControlQCOM: u32 = 2233;
    pub const glDisableDriverControlQCOM: u32 = 2234;
    pub const glExtGetTexturesQCOM: u32 = 2235;
    pub const glExtGetBuffersQCOM: u32 = 2236;
    pub const glExtGetRenderbuffersQCOM: u32 = 2237;
    pub const glExtGetFramebuffersQCOM: u32 = 2238;
    pub const glExtGetTexLevelParameterivQCOM: u32 = 2239;
    pub const glExtTexObjectStateOverrideiQCOM: u32 = 2240;
    pub const glExtGetTexSubImageQCOM: u32 = 2241;
    pub const glExtGetBufferPointervQCOM: u32 = 2242;
    pub const glExtGetShadersQCOM: u32 = 2243;
    pub const glExtGetProgramsQCOM: u32 = 2244;
    pub const glExtIsProgramBinaryQCOM: u32 = 2245;
    pub const glExtGetProgramBinarySourceQCOM: u32 = 2246;
    pub const glStartTilingQCOM: u32 = 2247;
    pub const glEndTilingQCOM: u32 = 2248;
    pub const glVertexAttribPointerData: u32 = 2249;
    pub const glVertexAttribPointerOffset: u32 = 2250;
    pub const glDrawElementsOffset: u32 = 2251;
    pub const glDrawElementsData: u32 = 2252;
    pub const glGetCompressedTextureFormats: u32 = 2253;
    pub const glShaderString: u32 = 2254;
    pub const glFinishRoundTrip: u32 = 2255;
    pub const glGenVertexArrays: u32 = 2256;
    pub const glBindVertexArray: u32 = 2257;
    pub const glDeleteVertexArrays: u32 = 2258;
    pub const glIsVertexArray: u32 = 2259;
    pub const glMapBufferRange: u32 = 2260;
    pub const glUnmapBuffer: u32 = 2261;
    pub const glFlushMappedBufferRange: u32 = 2262;
    pub const glMapBufferRangeAEMU: u32 = 2263;
    pub const glUnmapBufferAEMU: u32 = 2264;
    pub const glFlushMappedBufferRangeAEMU: u32 = 2265;
    pub const glReadPixelsOffsetAEMU: u32 = 2266;
    pub const glCompressedTexImage2DOffsetAEMU: u32 = 2267;
    pub const glCompressedTexSubImage2DOffsetAEMU: u32 = 2268;
    pub const glTexImage2DOffsetAEMU: u32 = 2269;
    pub const glTexSubImage2DOffsetAEMU: u32 = 2270;
    pub const glBindBufferRange: u32 = 2271;
    pub const glBindBufferBase: u32 = 2272;
    pub const glCopyBufferSubData: u32 = 2273;
    pub const glClearBufferiv: u32 = 2274;
    pub const glClearBufferuiv: u32 = 2275;
    pub const glClearBufferfv: u32 = 2276;
    pub const glClearBufferfi: u32 = 2277;
    pub const glGetBufferParameteri64v: u32 = 2278;
    pub const glGetBufferPointerv: u32 = 2279;
    pub const glUniformBlockBinding: u32 = 2280;
    pub const glGetUniformBlockIndex: u32 = 2281;
    pub const glGetUniformIndices: u32 = 2282;
    pub const glGetUniformIndicesAEMU: u32 = 2283;
    pub const glGetActiveUniformBlockiv: u32 = 2284;
    pub const glGetActiveUniformBlockName: u32 = 2285;
    pub const glUniform1ui: u32 = 2286;
    pub const glUniform2ui: u32 = 2287;
    pub const glUniform3ui: u32 = 2288;
    pub const glUniform4ui: u32 = 2289;
    pub const glUniform1uiv: u32 = 2290;
    pub const glUniform2uiv: u32 = 2291;
    pub const glUniform3uiv: u32 = 2292;
    pub const glUniform4uiv: u32 = 2293;
    pub const glUniformMatrix2x3fv: u32 = 2294;
    pub const glUniformMatrix3x2fv: u32 = 2295;
    pub const glUniformMatrix2x4fv: u32 = 2296;
    pub const glUniformMatrix4x2fv: u32 = 2297;
    pub const glUniformMatrix3x4fv: u32 = 2298;
    pub const glUniformMatrix4x3fv: u32 = 2299;
    pub const glGetUniformuiv: u32 = 2300;
    pub const glGetActiveUniformsiv: u32 = 2301;
    pub const glVertexAttribI4i: u32 = 2302;
    pub const glVertexAttribI4ui: u32 = 2303;
    pub const glVertexAttribI4iv: u32 = 2304;
    pub const glVertexAttribI4uiv: u32 = 2305;
    pub const glVertexAttribIPointer: u32 = 2306;
    pub const glVertexAttribIPointerOffsetAEMU: u32 = 2307;
    pub const glVertexAttribIPointerDataAEMU: u32 = 2308;
    pub const glGetVertexAttribIiv: u32 = 2309;
    pub const glGetVertexAttribIuiv: u32 = 2310;
    pub const glVertexAttribDivisor: u32 = 2311;
    pub const glDrawArraysInstanced: u32 = 2312;
    pub const glDrawElementsInstanced: u32 = 2313;
    pub const glDrawElementsInstancedDataAEMU: u32 = 2314;
    pub const glDrawElementsInstancedOffsetAEMU: u32 = 2315;
    pub const glDrawRangeElements: u32 = 2316;
    pub const glDrawRangeElementsDataAEMU: u32 = 2317;
    pub const glDrawRangeElementsOffsetAEMU: u32 = 2318;
    pub const glFenceSync: u32 = 2319;
    pub const glClientWaitSync: u32 = 2320;
    pub const glWaitSync: u32 = 2321;
    pub const glDeleteSync: u32 = 2322;
    pub const glIsSync: u32 = 2323;
    pub const glGetSynciv: u32 = 2324;
    pub const glFenceSyncAEMU: u32 = 2325;
    pub const glClientWaitSyncAEMU: u32 = 2326;
    pub const glWaitSyncAEMU: u32 = 2327;
    pub const glDeleteSyncAEMU: u32 = 2328;
    pub const glIsSyncAEMU: u32 = 2329;
    pub const glGetSyncivAEMU: u32 = 2330;
    pub const glDrawBuffers: u32 = 2331;
    pub const glReadBuffer: u32 = 2332;
    pub const glBlitFramebuffer: u32 = 2333;
    pub const glInvalidateFramebuffer: u32 = 2334;
    pub const glInvalidateSubFramebuffer: u32 = 2335;
    pub const glFramebufferTextureLayer: u32 = 2336;
    pub const glRenderbufferStorageMultisample: u32 = 2337;
    pub const glTexStorage2D: u32 = 2338;
    pub const glGetInternalformativ: u32 = 2339;
    pub const glBeginTransformFeedback: u32 = 2340;
    pub const glEndTransformFeedback: u32 = 2341;
    pub const glGenTransformFeedbacks: u32 = 2342;
    pub const glDeleteTransformFeedbacks: u32 = 2343;
    pub const glBindTransformFeedback: u32 = 2344;
    pub const glPauseTransformFeedback: u32 = 2345;
    pub const glResumeTransformFeedback: u32 = 2346;
    pub const glIsTransformFeedback: u32 = 2347;
    pub const glTransformFeedbackVaryings: u32 = 2348;
    pub const glTransformFeedbackVaryingsAEMU: u32 = 2349;
    pub const glGetTransformFeedbackVarying: u32 = 2350;
    pub const glGenSamplers: u32 = 2351;
    pub const glDeleteSamplers: u32 = 2352;
    pub const glBindSampler: u32 = 2353;
    pub const glSamplerParameterf: u32 = 2354;
    pub const glSamplerParameteri: u32 = 2355;
    pub const glSamplerParameterfv: u32 = 2356;
    pub const glSamplerParameteriv: u32 = 2357;
    pub const glGetSamplerParameterfv: u32 = 2358;
    pub const glGetSamplerParameteriv: u32 = 2359;
    pub const glIsSampler: u32 = 2360;
    pub const glGenQueries: u32 = 2361;
    pub const glDeleteQueries: u32 = 2362;
    pub const glBeginQuery: u32 = 2363;
    pub const glEndQuery: u32 = 2364;
    pub const glGetQueryiv: u32 = 2365;
    pub const glGetQueryObjectuiv: u32 = 2366;
    pub const glIsQuery: u32 = 2367;
    pub const glProgramParameteri: u32 = 2368;
    pub const glProgramBinary: u32 = 2369;
    pub const glGetProgramBinary: u32 = 2370;
    pub const glGetFragDataLocation: u32 = 2371;
    pub const glGetInteger64v: u32 = 2372;
    pub const glGetIntegeri_v: u32 = 2373;
    pub const glGetInteger64i_v: u32 = 2374;
    pub const glTexImage3D: u32 = 2375;
    pub const glTexImage3DOffsetAEMU: u32 = 2376;
    pub const glTexStorage3D: u32 = 2377;
    pub const glTexSubImage3D: u32 = 2378;
    pub const glTexSubImage3DOffsetAEMU: u32 = 2379;
    pub const glCompressedTexImage3D: u32 = 2380;
    pub const glCompressedTexImage3DOffsetAEMU: u32 = 2381;
    pub const glCompressedTexSubImage3D: u32 = 2382;
    pub const glCompressedTexSubImage3DOffsetAEMU: u32 = 2383;
    pub const glCopyTexSubImage3D: u32 = 2384;
    pub const glGetStringi: u32 = 2385;
    pub const glGetBooleani_v: u32 = 2386;
    pub const glMemoryBarrier: u32 = 2387;
    pub const glMemoryBarrierByRegion: u32 = 2388;
    pub const glGenProgramPipelines: u32 = 2389;
    pub const glDeleteProgramPipelines: u32 = 2390;
    pub const glBindProgramPipeline: u32 = 2391;
    pub const glGetProgramPipelineiv: u32 = 2392;
    pub const glGetProgramPipelineInfoLog: u32 = 2393;
    pub const glValidateProgramPipeline: u32 = 2394;
    pub const glIsProgramPipeline: u32 = 2395;
    pub const glUseProgramStages: u32 = 2396;
    pub const glActiveShaderProgram: u32 = 2397;
    pub const glCreateShaderProgramv: u32 = 2398;
    pub const glCreateShaderProgramvAEMU: u32 = 2399;
    pub const glProgramUniform1f: u32 = 2400;
    pub const glProgramUniform2f: u32 = 2401;
    pub const glProgramUniform3f: u32 = 2402;
    pub const glProgramUniform4f: u32 = 2403;
    pub const glProgramUniform1i: u32 = 2404;
    pub const glProgramUniform2i: u32 = 2405;
    pub const glProgramUniform3i: u32 = 2406;
    pub const glProgramUniform4i: u32 = 2407;
    pub const glProgramUniform1ui: u32 = 2408;
    pub const glProgramUniform2ui: u32 = 2409;
    pub const glProgramUniform3ui: u32 = 2410;
    pub const glProgramUniform4ui: u32 = 2411;
    pub const glProgramUniform1fv: u32 = 2412;
    pub const glProgramUniform2fv: u32 = 2413;
    pub const glProgramUniform3fv: u32 = 2414;
    pub const glProgramUniform4fv: u32 = 2415;
    pub const glProgramUniform1iv: u32 = 2416;
    pub const glProgramUniform2iv: u32 = 2417;
    pub const glProgramUniform3iv: u32 = 2418;
    pub const glProgramUniform4iv: u32 = 2419;
    pub const glProgramUniform1uiv: u32 = 2420;
    pub const glProgramUniform2uiv: u32 = 2421;
    pub const glProgramUniform3uiv: u32 = 2422;
    pub const glProgramUniform4uiv: u32 = 2423;
    pub const glProgramUniformMatrix2fv: u32 = 2424;
    pub const glProgramUniformMatrix3fv: u32 = 2425;
    pub const glProgramUniformMatrix4fv: u32 = 2426;
    pub const glProgramUniformMatrix2x3fv: u32 = 2427;
    pub const glProgramUniformMatrix3x2fv: u32 = 2428;
    pub const glProgramUniformMatrix2x4fv: u32 = 2429;
    pub const glProgramUniformMatrix4x2fv: u32 = 2430;
    pub const glProgramUniformMatrix3x4fv: u32 = 2431;
    pub const glProgramUniformMatrix4x3fv: u32 = 2432;
    pub const glGetProgramInterfaceiv: u32 = 2433;
    pub const glGetProgramResourceiv: u32 = 2434;
    pub const glGetProgramResourceIndex: u32 = 2435;
    pub const glGetProgramResourceLocation: u32 = 2436;
    pub const glGetProgramResourceName: u32 = 2437;
    pub const glBindImageTexture: u32 = 2438;
    pub const glDispatchCompute: u32 = 2439;
    pub const glDispatchComputeIndirect: u32 = 2440;
    pub const glBindVertexBuffer: u32 = 2441;
    pub const glVertexAttribBinding: u32 = 2442;
    pub const glVertexAttribFormat: u32 = 2443;
    pub const glVertexAttribIFormat: u32 = 2444;
    pub const glVertexBindingDivisor: u32 = 2445;
    pub const glDrawArraysIndirect: u32 = 2446;
    pub const glDrawArraysIndirectDataAEMU: u32 = 2447;
    pub const glDrawArraysIndirectOffsetAEMU: u32 = 2448;
    pub const glDrawElementsIndirect: u32 = 2449;
    pub const glDrawElementsIndirectDataAEMU: u32 = 2450;
    pub const glDrawElementsIndirectOffsetAEMU: u32 = 2451;
    pub const glTexStorage2DMultisample: u32 = 2452;
    pub const glSampleMaski: u32 = 2453;
    pub const glGetMultisamplefv: u32 = 2454;
    pub const glFramebufferParameteri: u32 = 2455;
    pub const glGetFramebufferParameteriv: u32 = 2456;
    pub const glGetTexLevelParameterfv: u32 = 2457;
    pub const glGetTexLevelParameteriv: u32 = 2458;
    pub const glMapBufferRangeDMA: u32 = 2459;
    pub const glUnmapBufferDMA: u32 = 2460;
    pub const glMapBufferRangeDirect: u32 = 2461;
    pub const glUnmapBufferDirect: u32 = 2462;
    pub const glFlushMappedBufferRangeDirect: u32 = 2463;
    pub const glGetGraphicsResetStatusEXT: u32 = 2464;
    pub const glReadnPixelsEXT: u32 = 2465;
    pub const glGetnUniformfvEXT: u32 = 2466;
    pub const glGetnUniformivEXT: u32 = 2467;
    pub const glDrawArraysNullAEMU: u32 = 2468;
    pub const glDrawElementsNullAEMU: u32 = 2469;
    pub const glDrawElementsOffsetNullAEMU: u32 = 2470;
    pub const glDrawElementsDataNullAEMU: u32 = 2471;
    pub const glUnmapBufferAsyncAEMU: u32 = 2472;
    pub const glFlushMappedBufferRangeAEMU2: u32 = 2473;
    pub const glBufferDataSyncAEMU: u32 = 2474;
    pub const glTexBufferOES: u32 = 2475;
    pub const glTexBufferRangeOES: u32 = 2476;
    pub const glTexBufferEXT: u32 = 2477;
    pub const glTexBufferRangeEXT: u32 = 2478;
    pub const glEnableiEXT: u32 = 2479;
    pub const glDisableiEXT: u32 = 2480;
    pub const glBlendEquationiEXT: u32 = 2481;
    pub const glBlendEquationSeparateiEXT: u32 = 2482;
    pub const glBlendFunciEXT: u32 = 2483;
    pub const glBlendFuncSeparateiEXT: u32 = 2484;
    pub const glColorMaskiEXT: u32 = 2485;
    pub const glIsEnablediEXT: u32 = 2486;
}
