#
# Vetro-specific parts of the product, on top of the Cuttlefish vendor.
#

PRODUCT_SOONG_NAMESPACES += device/vetro/vetro_arm64

# fstab of the virt: in vendor (second stage) and in the vendor_ramdisk (first
# stage, first_stage_ramdisk/fstab.vetro). Selected by androidboot.fstab_suffix.
PRODUCT_PACKAGES += \
    fstab.vetro \
    fstab.vetro.vendor_ramdisk

# init and ueventd of the board.
PRODUCT_COPY_FILES += \
    device/vetro/vetro_arm64/init.vetro.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vetro.rc

# Network: eth0 stays eth0 and is managed by EthernetService with DHCP (Vetro's
# stack or QEMU's slirp). Cuttlefish renames it and goes through simulated
# Wi-Fi to an OpenWRT on the host, which does not exist here.
PRODUCT_VENDOR_PROPERTIES += \
    ro.vendor.disable_rename_eth0=1

# adbd on TCP 5555 without authorisation: ONLY in the userdebug development
# build (Cuttlefish does the same: shared/device.mk already sets
# persist.adb.tcp.port=5555 and ro.adb.secure=0). A build for users must
# drop ro.adb.secure=0 and use adb keys (ADR 0022).
PRODUCT_SYSTEM_EXT_PROPERTIES += \
    ro.adb.secure=0

# No lock screen on first boot (LockSettingsService): it goes straight
# to the home screen, as analysis requires.
PRODUCT_PRODUCT_PROPERTIES += \
    ro.lockscreen.disable.default=true

# ART: Vetro CPU = Cortex-A53, ARMv8.0 + CRC32 + crypto (ADR 0005).
# TARGET_CPU_VARIANT := cortex-a53 (Cuttlefish's BoardConfig) makes the build
# write dalvik.vm.isa.arm64.variant=cortex-a53 and features=default in
# vendor/build.prop; tools/aosp/fetch.sh checks it on the artifacts. With
# newer variants the JIT would generate LSE and FP16, which the CPU lacks.

# microG (GmsCore and Companion) as privileged apps, with signature
# spoofing restricted to their certificates (guest/aosp/patches/frameworks/base).
PRODUCT_PACKAGES += \
    VetroGmsCore \
    VetroGmsCompanion \
    privapp-permissions-vetro-microg.xml \
    default-permissions-vetro-microg.xml \
    sysconfig-vetro-microg.xml

# Vetro development CA (ADR 0030): no module here. The certificate enters
# the system trust store through two patches (guest/aosp/patches/external/
# conscrypt and system/ca-certificates, tools/aosp/dev-ca.sh), because AOSP 15
# reads the CAs from /apex/com.android.conscrypt/cacerts and the APEX is built
# from its own project.

# Branding (ADR 0030): the product does not present itself as "Android".
# - static overlays: default icon of apps and of the package
#   installer without the robot; VetroFrameworkOverlay removes QuickSearchBox
#   (the "Google" widget on the Launcher3 home screen);
# - our own default wallpaper (WallpaperManager.openDefaultWallpaper reads
#   ro.config.wallpaper first), generated by tools/aosp/wallpaper.py;
# - ro.product.system.* like the other partitions (generic_system.mk sets
#   Android/mainline/generic, meant for the GSI).
PRODUCT_PACKAGES += \
    VetroFrameworkOverlay \
    VetroPackageInstallerOverlay
PRODUCT_COPY_FILES += \
    device/vetro/vetro_arm64/branding/wallpaper.png:$(TARGET_COPY_OUT_PRODUCT)/media/wallpaper/vetro.png
PRODUCT_PRODUCT_PROPERTIES += \
    ro.config.wallpaper=/product/media/wallpaper/vetro.png

# File manager daemon (ADR 0020): vsock, port 5200, only in development
# builds (vetro-files/vetro-files.rc). The source comes from
# guest/kernel/initramfs via tools/aosp/sync.sh.
PRODUCT_PACKAGES += vetro-files
