//! Interfaces to the engine that runs the WASM modules (docs/specs/jit.md).

/// Entries of the `env.tbl` function table that every engine provides to the
/// system-mode dispatcher: the engine places the blocks there
/// ([`Engine::place`]) and the dispatcher calls them with `call_indirect`.
pub const TABLE_SIZE: u32 = 1 << 18;

/// WASM engine: compiles the translator's modules and runs their blocks.
///
/// The implementations: `vetro-jit-native` (wasmtime, tests and `vetro --jit`)
/// and, in `vetro-wasm`, JavaScript's `WebAssembly`.
///
/// Every module is instantiated with the imports `env.mem` (the memory of
/// [`memory`](Self::memory)), `env.ld`/`env.st`/`env.resolve` (which
/// call the run's [`Host`]) and, if it declares it, `env.tbl`: a
/// `funcref` table of [`TABLE_SIZE`] entries, the same until the next
/// [`reset`](Self::reset). Only the dispatcher imports the table (V8 gives
/// every instance that imports a table its own dispatch table as large
/// as that one) and `env.resolve`.
pub trait Engine {
    type Module;
    /// Installs the runtime module (`translate::runtime`, ADR 0024): the
    /// engine instantiates it with the `env.*` imports and offers its exports as
    /// `rt.<name>` imports to all modules compiled afterwards. It stays installed
    /// even after [`reset`](Self::reset) (the engine re-instantiates it if needed).
    fn runtime(&mut self, wasm: &[u8]) -> Result<(), String>;
    /// Compiles a WASM module generated by the translator.
    fn compile(&mut self, wasm: &[u8]) -> Result<Self::Module, String>;
    /// True once the module can run. An engine may compile in the
    /// background (ADR 0038: the browser compiles in a Worker): until then
    /// its regions run in the interpreter, so the guest sees the same
    /// execution. Readiness may change only between two calls to the
    /// system JIT's `run`. The default: always ready.
    fn ready(&mut self, _m: &Self::Module) -> bool {
        true
    }
    /// Runs block `index` of the module on the state at address
    /// `state` of the shared memory; `ld`/`st` call `host`.
    fn run(&mut self, m: &Self::Module, index: u32, state: u32, host: &mut dyn Host) -> u32;
    /// The shared memory (where `JitState` lives).
    fn memory(&mut self) -> &mut [u8];
    /// Places the exports `b0`..`b<count-1>` of the module in entries `base..`
    /// of the `env.tbl` table. The default refuses: it is only needed by
    /// system mode.
    fn place(&mut self, _m: &Self::Module, _count: u32, _base: u32) {
        unimplemented!("this engine has no block table");
    }
    /// Discards all compiled modules (and may recreate the shared memory
    /// and the table): the caller will not use them any more. Needed by
    /// engines that do not free modules by themselves (wasmtime keeps every
    /// instance until the end of the store) and when the table is full.
    fn reset(&mut self) {}
    /// Ensures that [`memory`](Self::memory) has at least `bytes` bytes.
    /// The default only checks.
    fn reserve(&mut self, bytes: usize) {
        assert!(self.memory().len() >= bytes, "JIT engine memory too small: {bytes} bytes needed");
    }
    /// Address in the `env.mem` memory of the host's `len` bytes that
    /// start at `p`, if the blocks can reach them directly
    /// (in the browser `env.mem` is vetro-wasm's own memory). `None`: the
    /// blocks always go through `ld`/`st`.
    fn host_address(&mut self, _p: *const u8, _len: usize) -> Option<u32> {
        None
    }
}

/// Guest memory accesses on behalf of the blocks (`env.ld`,
/// `env.st`). An error is a fault: the engine writes
/// `JitState::exit_detail = FAULT` and the block exits. `mem` is the
/// engine's memory (that of [`Engine::memory`]): the host may update the
/// blocks' software TLB in it.
// The signature is the spec's (docs/specs/jit.md): the fault has no details,
// which stay with the host.
#[allow(clippy::result_unit_err)]
pub trait Host {
    fn ld(&mut self, mem: &mut [u8], va: u64, size: u32) -> Result<u64, ()>;
    /// Ok(true) = stop after this instruction.
    fn st(&mut self, mem: &mut [u8], va: u64, size: u32, value: u64) -> Result<bool, ()>;
    /// The dispatcher's `env.resolve`: the jump cache entry for the `pc` of
    /// `JitState` is missing; true if the host wrote it (the dispatcher
    /// continues), false if the dispatcher must return to the host with `NEXT`.
    fn resolve(&mut self, _mem: &mut [u8]) -> bool {
        false
    }
    /// `env.vsync` (ADR 0024): copies the SIMD/FP registers of the `Cpu` into the
    /// `JitState` at address `state` of `mem` and sets `v_valid` = 1
    /// ([`crate::state::vsync_in`]). It is called by the first region of the run
    /// that uses the SIMD registers; whoever copies the state back into the `Cpu`
    /// also brings back the registers if `v_valid`.
    fn vsync(&mut self, _mem: &mut [u8], _state: u32) {
        unreachable!("this host has no SIMD registers");
    }
}
