#!/usr/bin/env python3
"""Generates crates/vetro-gfxstream/src/tables.rs from gfxstream's emugen
specs (crates/vetro-gfxstream/spec/*.in, *.attrib, *.types, Apache 2.0,
hardware/google/gfxstream/codegen of android-15.0.0_r36).

Wire format of one call (emugen, what gles2_dec.cpp / renderControl_dec.cpp
decode): u32 opcode, u32 total packet length, then the parameters in order:
- a scalar: as many bytes as its .types width (GLboolean 1, GLsync/uint64_t 8,
  every pointer-sized or 32-bit type 4);
- a pointer "in" (default): u32 size, then size bytes;
- a pointer "out": u32 size only; the bytes go back in the reply;
- a DMA pointer (var_flag DMA): a u64 guest physical address, no size.
The reply of a call is its "out" buffers in order, then the return value
(its .types width), nothing if both are absent. No checksum (the host never
advertises ANDROID_EMU_CHECKSUM_HELPER).

Usage: tools/gfxstream/gen-tables.py  (rewrites the file; CI checks it is
up to date with --check).
"""
import os
import re
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..')
SPEC = os.path.join(ROOT, 'crates', 'vetro-gfxstream', 'spec')
OUT = os.path.join(ROOT, 'crates', 'vetro-gfxstream', 'src', 'tables.rs')

APIS = [
    # (name in Rust, spec base name, base opcode)
    ('RC', 'renderControl', 10000),
    ('GLES2', 'gles2', 2048),
]


def read_types(path):
    widths = {}
    for line in open(path):
        parts = line.split()
        if len(parts) >= 2:
            widths[parts[0]] = int(parts[1])
    return widths


def read_entries(path):
    entries = []
    for line in open(path):
        line = line.strip()
        m = re.match(r'GL_EN(?:TRY|RTY)\((.*)\)\s*;?\s*$', line)
        if not m:
            continue
        fields = [f.strip() for f in m.group(1).split(',')]
        ret, name, params = fields[0], fields[1], fields[2:]
        ps = []
        for p in params:
            if not p or p == 'void':
                continue
            m2 = re.match(r'(.*?)([A-Za-z_][A-Za-z0-9_]*)$', p)
            ty, pname = m2.group(1).strip(), m2.group(2)
            ty = re.sub(r'\bconst\b', '', ty)
            ty = re.sub(r'\s+', '', ty)
            ps.append((ty, pname))
        entries.append((ret.strip(), name, ps))
    return entries


def read_attribs(path):
    attrs = {}
    cur = None
    for line in open(path):
        if line.startswith('#') or not line.strip():
            continue
        if not line[0].isspace():
            cur = line.strip()
            attrs.setdefault(cur, {'dir': {}, 'flags': set(), 'var_flags': {}})
            continue
        if cur is None:
            continue
        parts = line.split()
        if parts[0] == 'dir':
            attrs[cur]['dir'][parts[1]] = parts[2]
        elif parts[0] == 'var_flag':
            attrs[cur]['var_flags'].setdefault(parts[1], set()).update(parts[2:])
        elif parts[0] == 'flag':
            attrs[cur]['flags'].update(parts[1:])
    return attrs


def width(widths, ty):
    if ty in widths:
        return widths[ty]
    if ty.endswith('*'):
        return 32
    # C types emugen knows without a .types line.
    builtin = {'int': 32, 'unsigned': 32, 'float': 32, 'char': 8}
    if ty in builtin:
        return builtin[ty]
    raise SystemExit(f'unknown type {ty}')


def gen():
    out = []
    out.append('// Generated by tools/gfxstream/gen-tables.py from spec/*.in, *.attrib, *.types')
    out.append('// (gfxstream emugen specs, Apache 2.0). Do not edit.')
    out.append('')
    out.append('use crate::wire::{Op, P};')
    out.append('')
    for rust, base, opbase in APIS:
        widths = read_types(os.path.join(SPEC, base + '.types'))
        entries = read_entries(os.path.join(SPEC, base + '.in'))
        attrs = read_attribs(os.path.join(SPEC, base + '.attrib'))
        out.append(f'pub const {rust}_BASE: u32 = {opbase};')
        out.append(f'pub static {rust}: [Op; {len(entries)}] = [')
        for ret, name, ps in entries:
            a = attrs.get(name, {'dir': {}, 'flags': set(), 'var_flags': {}})
            kinds = []
            for ty, pname in ps:
                vf = a['var_flags'].get(pname, set())
                if ty.endswith('*'):
                    if 'DMA' in vf:
                        kinds.append('P::S8')
                    elif a['dir'].get(pname, 'in') == 'out':
                        kinds.append('P::Out')
                    else:
                        kinds.append('P::In')
                else:
                    w = width(widths, ty)
                    kinds.append({8: 'P::S1', 16: 'P::S2', 32: 'P::S4', 64: 'P::S8'}[w])
            rw = 0 if ret == 'void' else width(widths, ret) // 8
            out.append(f'    Op {{ name: "{name}", params: &[{", ".join(kinds)}], ret: {rw} }},')
        out.append('];')
        out.append('')
        out.append('#[allow(non_upper_case_globals, dead_code)]')
        out.append(f'pub mod {rust.lower()} {{')
        for i, (_, name, _) in enumerate(entries):
            out.append(f'    pub const {name}: u32 = {opbase + i};')
        out.append('}')
        out.append('')
    return '\n'.join(out)


if __name__ == '__main__':
    text = gen()
    if '--check' in sys.argv:
        if open(OUT).read() != text:
            raise SystemExit(f'{OUT} is stale: run tools/gfxstream/gen-tables.py')
    else:
        open(OUT, 'w').write(text)
